; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Optimus"
#define MyAppVersion "0.10.2"
#define MyAppPublisher "Neuroxess, Inc."
#define MyAppURL "https://www.neuroxess.com/"
#define MyAppExeName "Optimus.exe"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A4669927-B660-40C3-A4FA-0A384EDBD950}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=.\installation\license.txt
InfoBeforeFile=.\installation\infomationBeforeInstall.txt
InfoAfterFile=.\installation\infomationAfterInstall.txt
; Uncomment the following line to run in non-administrative install mode (install for the current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename={#MyAppName} {#MyAppVersion}
SetupIconFile=.\installation\logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
DefaultDirName=C:\Optimus
PrivilegesRequired=admin

[Languages]
Name: "chinesesimp"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: ".\bin\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: ".\config\*"; DestDir: "{app}\config"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\Publishes\Dependency\winsdksetup.exe"; DestDir: "{app}\bin";  
Source: "E:\Publishes\Dependency\vcruntime140d.dll"; DestDir: "{app}\bin";  

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"; Tasks: desktopicon

[Run]
  Filename: "{app}\bin\winsdksetup.exe"; \
 Description: "setupwinsdk"; \
 Flags: shellexec postinstall nowait
  Filename: "{app}\bin\{#MyAppExeName}"; \
 Description: "startOptimus"; \
 Flags: shellexec postinstall nowait
 Filename: "{app}\bin\NxBackup.bat"; \
 Flags: nowait skipifdoesntexist