// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: BackupRes.proto

#include "BackupRes.pb.h"
#include "BackupRes.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace BackupRes {

static const char* BackupResService_method_names[] = {
  "/BackupRes.BackupResService/setBackup",
  "/BackupRes.BackupResService/setRestore",
};

std::unique_ptr< BackupResService::Stub> BackupResService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BackupResService::Stub> stub(new BackupResService::Stub(channel, options));
  return stub;
}

BackupResService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_setBackup_(BackupResService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setRestore_(BackupResService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status BackupResService::Stub::setBackup(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::BackupRes::Backup* response) {
  return ::grpc::internal::BlockingUnaryCall< ::BackupRes::Backup, ::BackupRes::Backup, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setBackup_, context, request, response);
}

void BackupResService::Stub::async::setBackup(::grpc::ClientContext* context, const ::BackupRes::Backup* request, ::BackupRes::Backup* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::BackupRes::Backup, ::BackupRes::Backup, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setBackup_, context, request, response, std::move(f));
}

void BackupResService::Stub::async::setBackup(::grpc::ClientContext* context, const ::BackupRes::Backup* request, ::BackupRes::Backup* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setBackup_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::BackupRes::Backup>* BackupResService::Stub::PrepareAsyncsetBackupRaw(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::BackupRes::Backup, ::BackupRes::Backup, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setBackup_, context, request);
}

::grpc::ClientAsyncResponseReader< ::BackupRes::Backup>* BackupResService::Stub::AsyncsetBackupRaw(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetBackupRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BackupResService::Stub::setRestore(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::BackupRes::Restore* response) {
  return ::grpc::internal::BlockingUnaryCall< ::BackupRes::Restore, ::BackupRes::Restore, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setRestore_, context, request, response);
}

void BackupResService::Stub::async::setRestore(::grpc::ClientContext* context, const ::BackupRes::Restore* request, ::BackupRes::Restore* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::BackupRes::Restore, ::BackupRes::Restore, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setRestore_, context, request, response, std::move(f));
}

void BackupResService::Stub::async::setRestore(::grpc::ClientContext* context, const ::BackupRes::Restore* request, ::BackupRes::Restore* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setRestore_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::BackupRes::Restore>* BackupResService::Stub::PrepareAsyncsetRestoreRaw(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::BackupRes::Restore, ::BackupRes::Restore, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setRestore_, context, request);
}

::grpc::ClientAsyncResponseReader< ::BackupRes::Restore>* BackupResService::Stub::AsyncsetRestoreRaw(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetRestoreRaw(context, request, cq);
  result->StartCall();
  return result;
}

BackupResService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BackupResService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BackupResService::Service, ::BackupRes::Backup, ::BackupRes::Backup, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BackupResService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::BackupRes::Backup* req,
             ::BackupRes::Backup* resp) {
               return service->setBackup(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BackupResService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BackupResService::Service, ::BackupRes::Restore, ::BackupRes::Restore, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BackupResService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::BackupRes::Restore* req,
             ::BackupRes::Restore* resp) {
               return service->setRestore(ctx, req, resp);
             }, this)));
}

BackupResService::Service::~Service() {
}

::grpc::Status BackupResService::Service::setBackup(::grpc::ServerContext* context, const ::BackupRes::Backup* request, ::BackupRes::Backup* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BackupResService::Service::setRestore(::grpc::ServerContext* context, const ::BackupRes::Restore* request, ::BackupRes::Restore* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace BackupRes

