// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BackupRes.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_BackupRes_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_BackupRes_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_BackupRes_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_BackupRes_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BackupRes_2eproto;
namespace BackupRes {
class Backup;
struct BackupDefaultTypeInternal;
extern BackupDefaultTypeInternal _Backup_default_instance_;
class Restore;
struct RestoreDefaultTypeInternal;
extern RestoreDefaultTypeInternal _Restore_default_instance_;
}  // namespace BackupRes
PROTOBUF_NAMESPACE_OPEN
template<> ::BackupRes::Backup* Arena::CreateMaybeMessage<::BackupRes::Backup>(Arena*);
template<> ::BackupRes::Restore* Arena::CreateMaybeMessage<::BackupRes::Restore>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace BackupRes {

// ===================================================================

class Backup final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:BackupRes.Backup) */ {
 public:
  inline Backup() : Backup(nullptr) {}
  ~Backup() override;
  explicit constexpr Backup(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Backup(const Backup& from);
  Backup(Backup&& from) noexcept
    : Backup() {
    *this = ::std::move(from);
  }

  inline Backup& operator=(const Backup& from) {
    CopyFrom(from);
    return *this;
  }
  inline Backup& operator=(Backup&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Backup& default_instance() {
    return *internal_default_instance();
  }
  static inline const Backup* internal_default_instance() {
    return reinterpret_cast<const Backup*>(
               &_Backup_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Backup& a, Backup& b) {
    a.Swap(&b);
  }
  inline void Swap(Backup* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Backup* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Backup* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Backup>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Backup& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Backup& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Backup* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "BackupRes.Backup";
  }
  protected:
  explicit Backup(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBackpathFieldNumber = 1,
    kCopypathFieldNumber = 2,
    kBackupdateFieldNumber = 3,
  };
  // string backpath = 1;
  void clear_backpath();
  const std::string& backpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_backpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_backpath();
  PROTOBUF_NODISCARD std::string* release_backpath();
  void set_allocated_backpath(std::string* backpath);
  private:
  const std::string& _internal_backpath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_backpath(const std::string& value);
  std::string* _internal_mutable_backpath();
  public:

  // string copypath = 2;
  void clear_copypath();
  const std::string& copypath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_copypath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_copypath();
  PROTOBUF_NODISCARD std::string* release_copypath();
  void set_allocated_copypath(std::string* copypath);
  private:
  const std::string& _internal_copypath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_copypath(const std::string& value);
  std::string* _internal_mutable_copypath();
  public:

  // string backupdate = 3;
  void clear_backupdate();
  const std::string& backupdate() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_backupdate(ArgT0&& arg0, ArgT... args);
  std::string* mutable_backupdate();
  PROTOBUF_NODISCARD std::string* release_backupdate();
  void set_allocated_backupdate(std::string* backupdate);
  private:
  const std::string& _internal_backupdate() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_backupdate(const std::string& value);
  std::string* _internal_mutable_backupdate();
  public:

  // @@protoc_insertion_point(class_scope:BackupRes.Backup)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr backpath_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr copypath_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr backupdate_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_BackupRes_2eproto;
};
// -------------------------------------------------------------------

class Restore final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:BackupRes.Restore) */ {
 public:
  inline Restore() : Restore(nullptr) {}
  ~Restore() override;
  explicit constexpr Restore(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Restore(const Restore& from);
  Restore(Restore&& from) noexcept
    : Restore() {
    *this = ::std::move(from);
  }

  inline Restore& operator=(const Restore& from) {
    CopyFrom(from);
    return *this;
  }
  inline Restore& operator=(Restore&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Restore& default_instance() {
    return *internal_default_instance();
  }
  static inline const Restore* internal_default_instance() {
    return reinterpret_cast<const Restore*>(
               &_Restore_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Restore& a, Restore& b) {
    a.Swap(&b);
  }
  inline void Swap(Restore* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Restore* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Restore* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Restore>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Restore& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Restore& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Restore* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "BackupRes.Restore";
  }
  protected:
  explicit Restore(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRestorepathFieldNumber = 1,
    kOrgpathFieldNumber = 2,
    kRestoredateFieldNumber = 3,
  };
  // string restorepath = 1;
  void clear_restorepath();
  const std::string& restorepath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_restorepath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_restorepath();
  PROTOBUF_NODISCARD std::string* release_restorepath();
  void set_allocated_restorepath(std::string* restorepath);
  private:
  const std::string& _internal_restorepath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_restorepath(const std::string& value);
  std::string* _internal_mutable_restorepath();
  public:

  // string orgpath = 2;
  void clear_orgpath();
  const std::string& orgpath() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_orgpath(ArgT0&& arg0, ArgT... args);
  std::string* mutable_orgpath();
  PROTOBUF_NODISCARD std::string* release_orgpath();
  void set_allocated_orgpath(std::string* orgpath);
  private:
  const std::string& _internal_orgpath() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_orgpath(const std::string& value);
  std::string* _internal_mutable_orgpath();
  public:

  // string restoredate = 3;
  void clear_restoredate();
  const std::string& restoredate() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_restoredate(ArgT0&& arg0, ArgT... args);
  std::string* mutable_restoredate();
  PROTOBUF_NODISCARD std::string* release_restoredate();
  void set_allocated_restoredate(std::string* restoredate);
  private:
  const std::string& _internal_restoredate() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_restoredate(const std::string& value);
  std::string* _internal_mutable_restoredate();
  public:

  // @@protoc_insertion_point(class_scope:BackupRes.Restore)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr restorepath_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr orgpath_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr restoredate_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_BackupRes_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Backup

// string backpath = 1;
inline void Backup::clear_backpath() {
  backpath_.ClearToEmpty();
}
inline const std::string& Backup::backpath() const {
  // @@protoc_insertion_point(field_get:BackupRes.Backup.backpath)
  return _internal_backpath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Backup::set_backpath(ArgT0&& arg0, ArgT... args) {
 
 backpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:BackupRes.Backup.backpath)
}
inline std::string* Backup::mutable_backpath() {
  std::string* _s = _internal_mutable_backpath();
  // @@protoc_insertion_point(field_mutable:BackupRes.Backup.backpath)
  return _s;
}
inline const std::string& Backup::_internal_backpath() const {
  return backpath_.Get();
}
inline void Backup::_internal_set_backpath(const std::string& value) {
  
  backpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Backup::_internal_mutable_backpath() {
  
  return backpath_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Backup::release_backpath() {
  // @@protoc_insertion_point(field_release:BackupRes.Backup.backpath)
  return backpath_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Backup::set_allocated_backpath(std::string* backpath) {
  if (backpath != nullptr) {
    
  } else {
    
  }
  backpath_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), backpath,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (backpath_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    backpath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:BackupRes.Backup.backpath)
}

// string copypath = 2;
inline void Backup::clear_copypath() {
  copypath_.ClearToEmpty();
}
inline const std::string& Backup::copypath() const {
  // @@protoc_insertion_point(field_get:BackupRes.Backup.copypath)
  return _internal_copypath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Backup::set_copypath(ArgT0&& arg0, ArgT... args) {
 
 copypath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:BackupRes.Backup.copypath)
}
inline std::string* Backup::mutable_copypath() {
  std::string* _s = _internal_mutable_copypath();
  // @@protoc_insertion_point(field_mutable:BackupRes.Backup.copypath)
  return _s;
}
inline const std::string& Backup::_internal_copypath() const {
  return copypath_.Get();
}
inline void Backup::_internal_set_copypath(const std::string& value) {
  
  copypath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Backup::_internal_mutable_copypath() {
  
  return copypath_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Backup::release_copypath() {
  // @@protoc_insertion_point(field_release:BackupRes.Backup.copypath)
  return copypath_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Backup::set_allocated_copypath(std::string* copypath) {
  if (copypath != nullptr) {
    
  } else {
    
  }
  copypath_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), copypath,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (copypath_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    copypath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:BackupRes.Backup.copypath)
}

// string backupdate = 3;
inline void Backup::clear_backupdate() {
  backupdate_.ClearToEmpty();
}
inline const std::string& Backup::backupdate() const {
  // @@protoc_insertion_point(field_get:BackupRes.Backup.backupdate)
  return _internal_backupdate();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Backup::set_backupdate(ArgT0&& arg0, ArgT... args) {
 
 backupdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:BackupRes.Backup.backupdate)
}
inline std::string* Backup::mutable_backupdate() {
  std::string* _s = _internal_mutable_backupdate();
  // @@protoc_insertion_point(field_mutable:BackupRes.Backup.backupdate)
  return _s;
}
inline const std::string& Backup::_internal_backupdate() const {
  return backupdate_.Get();
}
inline void Backup::_internal_set_backupdate(const std::string& value) {
  
  backupdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Backup::_internal_mutable_backupdate() {
  
  return backupdate_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Backup::release_backupdate() {
  // @@protoc_insertion_point(field_release:BackupRes.Backup.backupdate)
  return backupdate_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Backup::set_allocated_backupdate(std::string* backupdate) {
  if (backupdate != nullptr) {
    
  } else {
    
  }
  backupdate_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), backupdate,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (backupdate_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    backupdate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:BackupRes.Backup.backupdate)
}

// -------------------------------------------------------------------

// Restore

// string restorepath = 1;
inline void Restore::clear_restorepath() {
  restorepath_.ClearToEmpty();
}
inline const std::string& Restore::restorepath() const {
  // @@protoc_insertion_point(field_get:BackupRes.Restore.restorepath)
  return _internal_restorepath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Restore::set_restorepath(ArgT0&& arg0, ArgT... args) {
 
 restorepath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:BackupRes.Restore.restorepath)
}
inline std::string* Restore::mutable_restorepath() {
  std::string* _s = _internal_mutable_restorepath();
  // @@protoc_insertion_point(field_mutable:BackupRes.Restore.restorepath)
  return _s;
}
inline const std::string& Restore::_internal_restorepath() const {
  return restorepath_.Get();
}
inline void Restore::_internal_set_restorepath(const std::string& value) {
  
  restorepath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Restore::_internal_mutable_restorepath() {
  
  return restorepath_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Restore::release_restorepath() {
  // @@protoc_insertion_point(field_release:BackupRes.Restore.restorepath)
  return restorepath_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Restore::set_allocated_restorepath(std::string* restorepath) {
  if (restorepath != nullptr) {
    
  } else {
    
  }
  restorepath_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), restorepath,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (restorepath_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    restorepath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:BackupRes.Restore.restorepath)
}

// string orgpath = 2;
inline void Restore::clear_orgpath() {
  orgpath_.ClearToEmpty();
}
inline const std::string& Restore::orgpath() const {
  // @@protoc_insertion_point(field_get:BackupRes.Restore.orgpath)
  return _internal_orgpath();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Restore::set_orgpath(ArgT0&& arg0, ArgT... args) {
 
 orgpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:BackupRes.Restore.orgpath)
}
inline std::string* Restore::mutable_orgpath() {
  std::string* _s = _internal_mutable_orgpath();
  // @@protoc_insertion_point(field_mutable:BackupRes.Restore.orgpath)
  return _s;
}
inline const std::string& Restore::_internal_orgpath() const {
  return orgpath_.Get();
}
inline void Restore::_internal_set_orgpath(const std::string& value) {
  
  orgpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Restore::_internal_mutable_orgpath() {
  
  return orgpath_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Restore::release_orgpath() {
  // @@protoc_insertion_point(field_release:BackupRes.Restore.orgpath)
  return orgpath_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Restore::set_allocated_orgpath(std::string* orgpath) {
  if (orgpath != nullptr) {
    
  } else {
    
  }
  orgpath_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), orgpath,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (orgpath_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    orgpath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:BackupRes.Restore.orgpath)
}

// string restoredate = 3;
inline void Restore::clear_restoredate() {
  restoredate_.ClearToEmpty();
}
inline const std::string& Restore::restoredate() const {
  // @@protoc_insertion_point(field_get:BackupRes.Restore.restoredate)
  return _internal_restoredate();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Restore::set_restoredate(ArgT0&& arg0, ArgT... args) {
 
 restoredate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:BackupRes.Restore.restoredate)
}
inline std::string* Restore::mutable_restoredate() {
  std::string* _s = _internal_mutable_restoredate();
  // @@protoc_insertion_point(field_mutable:BackupRes.Restore.restoredate)
  return _s;
}
inline const std::string& Restore::_internal_restoredate() const {
  return restoredate_.Get();
}
inline void Restore::_internal_set_restoredate(const std::string& value) {
  
  restoredate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Restore::_internal_mutable_restoredate() {
  
  return restoredate_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Restore::release_restoredate() {
  // @@protoc_insertion_point(field_release:BackupRes.Restore.restoredate)
  return restoredate_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Restore::set_allocated_restoredate(std::string* restoredate) {
  if (restoredate != nullptr) {
    
  } else {
    
  }
  restoredate_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), restoredate,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (restoredate_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    restoredate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:BackupRes.Restore.restoredate)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace BackupRes

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_BackupRes_2eproto
