// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BackupRes.proto

#include "BackupRes.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace BackupRes {
constexpr Backup::Backup(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : backpath_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , copypath_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , backupdate_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct BackupDefaultTypeInternal {
  constexpr BackupDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~BackupDefaultTypeInternal() {}
  union {
    Backup _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT BackupDefaultTypeInternal _Backup_default_instance_;
constexpr Restore::Restore(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : restorepath_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , orgpath_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , restoredate_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct RestoreDefaultTypeInternal {
  constexpr RestoreDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~RestoreDefaultTypeInternal() {}
  union {
    Restore _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT RestoreDefaultTypeInternal _Restore_default_instance_;
}  // namespace BackupRes
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_BackupRes_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_BackupRes_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_BackupRes_2eproto = nullptr;

const uint32_t TableStruct_BackupRes_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::BackupRes::Backup, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::BackupRes::Backup, backpath_),
  PROTOBUF_FIELD_OFFSET(::BackupRes::Backup, copypath_),
  PROTOBUF_FIELD_OFFSET(::BackupRes::Backup, backupdate_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::BackupRes::Restore, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::BackupRes::Restore, restorepath_),
  PROTOBUF_FIELD_OFFSET(::BackupRes::Restore, orgpath_),
  PROTOBUF_FIELD_OFFSET(::BackupRes::Restore, restoredate_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::BackupRes::Backup)},
  { 9, -1, -1, sizeof(::BackupRes::Restore)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::BackupRes::_Backup_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::BackupRes::_Restore_default_instance_),
};

const char descriptor_table_protodef_BackupRes_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017BackupRes.proto\022\tBackupRes\"@\n\006Backup\022\020"
  "\n\010backpath\030\001 \001(\t\022\020\n\010copypath\030\002 \001(\t\022\022\n\nba"
  "ckupdate\030\003 \001(\t\"D\n\007Restore\022\023\n\013restorepath"
  "\030\001 \001(\t\022\017\n\007orgpath\030\002 \001(\t\022\023\n\013restoredate\030\003"
  " \001(\t2\177\n\020BackupResService\0223\n\tsetBackup\022\021."
  "BackupRes.Backup\032\021.BackupRes.Backup\"\000\0226\n"
  "\nsetRestore\022\022.BackupRes.Restore\032\022.Backup"
  "Res.Restore\"\000B\022\n\020io.grpc.recorderb\006proto"
  "3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_BackupRes_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_BackupRes_2eproto = {
  false, false, 321, descriptor_table_protodef_BackupRes_2eproto, "BackupRes.proto", 
  &descriptor_table_BackupRes_2eproto_once, nullptr, 0, 2,
  schemas, file_default_instances, TableStruct_BackupRes_2eproto::offsets,
  file_level_metadata_BackupRes_2eproto, file_level_enum_descriptors_BackupRes_2eproto, file_level_service_descriptors_BackupRes_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_BackupRes_2eproto_getter() {
  return &descriptor_table_BackupRes_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_BackupRes_2eproto(&descriptor_table_BackupRes_2eproto);
namespace BackupRes {

// ===================================================================

class Backup::_Internal {
 public:
};

Backup::Backup(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:BackupRes.Backup)
}
Backup::Backup(const Backup& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  backpath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    backpath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_backpath().empty()) {
    backpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_backpath(), 
      GetArenaForAllocation());
  }
  copypath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    copypath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_copypath().empty()) {
    copypath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_copypath(), 
      GetArenaForAllocation());
  }
  backupdate_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    backupdate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_backupdate().empty()) {
    backupdate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_backupdate(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:BackupRes.Backup)
}

inline void Backup::SharedCtor() {
backpath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  backpath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
copypath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  copypath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
backupdate_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  backupdate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Backup::~Backup() {
  // @@protoc_insertion_point(destructor:BackupRes.Backup)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Backup::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  backpath_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  copypath_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  backupdate_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Backup::ArenaDtor(void* object) {
  Backup* _this = reinterpret_cast< Backup* >(object);
  (void)_this;
}
void Backup::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Backup::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Backup::Clear() {
// @@protoc_insertion_point(message_clear_start:BackupRes.Backup)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  backpath_.ClearToEmpty();
  copypath_.ClearToEmpty();
  backupdate_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Backup::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string backpath = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_backpath();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "BackupRes.Backup.backpath"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string copypath = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_copypath();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "BackupRes.Backup.copypath"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string backupdate = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_backupdate();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "BackupRes.Backup.backupdate"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Backup::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BackupRes.Backup)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string backpath = 1;
  if (!this->_internal_backpath().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_backpath().data(), static_cast<int>(this->_internal_backpath().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BackupRes.Backup.backpath");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_backpath(), target);
  }

  // string copypath = 2;
  if (!this->_internal_copypath().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_copypath().data(), static_cast<int>(this->_internal_copypath().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BackupRes.Backup.copypath");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_copypath(), target);
  }

  // string backupdate = 3;
  if (!this->_internal_backupdate().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_backupdate().data(), static_cast<int>(this->_internal_backupdate().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BackupRes.Backup.backupdate");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_backupdate(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BackupRes.Backup)
  return target;
}

size_t Backup::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BackupRes.Backup)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string backpath = 1;
  if (!this->_internal_backpath().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_backpath());
  }

  // string copypath = 2;
  if (!this->_internal_copypath().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_copypath());
  }

  // string backupdate = 3;
  if (!this->_internal_backupdate().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_backupdate());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Backup::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Backup::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Backup::GetClassData() const { return &_class_data_; }

void Backup::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Backup *>(to)->MergeFrom(
      static_cast<const Backup &>(from));
}


void Backup::MergeFrom(const Backup& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:BackupRes.Backup)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_backpath().empty()) {
    _internal_set_backpath(from._internal_backpath());
  }
  if (!from._internal_copypath().empty()) {
    _internal_set_copypath(from._internal_copypath());
  }
  if (!from._internal_backupdate().empty()) {
    _internal_set_backupdate(from._internal_backupdate());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Backup::CopyFrom(const Backup& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BackupRes.Backup)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Backup::IsInitialized() const {
  return true;
}

void Backup::InternalSwap(Backup* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &backpath_, lhs_arena,
      &other->backpath_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &copypath_, lhs_arena,
      &other->copypath_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &backupdate_, lhs_arena,
      &other->backupdate_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Backup::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_BackupRes_2eproto_getter, &descriptor_table_BackupRes_2eproto_once,
      file_level_metadata_BackupRes_2eproto[0]);
}

// ===================================================================

class Restore::_Internal {
 public:
};

Restore::Restore(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:BackupRes.Restore)
}
Restore::Restore(const Restore& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  restorepath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    restorepath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_restorepath().empty()) {
    restorepath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_restorepath(), 
      GetArenaForAllocation());
  }
  orgpath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    orgpath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_orgpath().empty()) {
    orgpath_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_orgpath(), 
      GetArenaForAllocation());
  }
  restoredate_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    restoredate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_restoredate().empty()) {
    restoredate_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_restoredate(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:BackupRes.Restore)
}

inline void Restore::SharedCtor() {
restorepath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  restorepath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
orgpath_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  orgpath_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
restoredate_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  restoredate_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Restore::~Restore() {
  // @@protoc_insertion_point(destructor:BackupRes.Restore)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Restore::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  restorepath_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  orgpath_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  restoredate_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Restore::ArenaDtor(void* object) {
  Restore* _this = reinterpret_cast< Restore* >(object);
  (void)_this;
}
void Restore::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Restore::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Restore::Clear() {
// @@protoc_insertion_point(message_clear_start:BackupRes.Restore)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  restorepath_.ClearToEmpty();
  orgpath_.ClearToEmpty();
  restoredate_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Restore::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string restorepath = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_restorepath();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "BackupRes.Restore.restorepath"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string orgpath = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_orgpath();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "BackupRes.Restore.orgpath"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string restoredate = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_restoredate();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "BackupRes.Restore.restoredate"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Restore::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BackupRes.Restore)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string restorepath = 1;
  if (!this->_internal_restorepath().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_restorepath().data(), static_cast<int>(this->_internal_restorepath().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BackupRes.Restore.restorepath");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_restorepath(), target);
  }

  // string orgpath = 2;
  if (!this->_internal_orgpath().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_orgpath().data(), static_cast<int>(this->_internal_orgpath().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BackupRes.Restore.orgpath");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_orgpath(), target);
  }

  // string restoredate = 3;
  if (!this->_internal_restoredate().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_restoredate().data(), static_cast<int>(this->_internal_restoredate().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BackupRes.Restore.restoredate");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_restoredate(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BackupRes.Restore)
  return target;
}

size_t Restore::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BackupRes.Restore)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string restorepath = 1;
  if (!this->_internal_restorepath().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_restorepath());
  }

  // string orgpath = 2;
  if (!this->_internal_orgpath().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_orgpath());
  }

  // string restoredate = 3;
  if (!this->_internal_restoredate().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_restoredate());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Restore::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Restore::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Restore::GetClassData() const { return &_class_data_; }

void Restore::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Restore *>(to)->MergeFrom(
      static_cast<const Restore &>(from));
}


void Restore::MergeFrom(const Restore& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:BackupRes.Restore)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_restorepath().empty()) {
    _internal_set_restorepath(from._internal_restorepath());
  }
  if (!from._internal_orgpath().empty()) {
    _internal_set_orgpath(from._internal_orgpath());
  }
  if (!from._internal_restoredate().empty()) {
    _internal_set_restoredate(from._internal_restoredate());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Restore::CopyFrom(const Restore& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BackupRes.Restore)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Restore::IsInitialized() const {
  return true;
}

void Restore::InternalSwap(Restore* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &restorepath_, lhs_arena,
      &other->restorepath_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &orgpath_, lhs_arena,
      &other->orgpath_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &restoredate_, lhs_arena,
      &other->restoredate_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Restore::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_BackupRes_2eproto_getter, &descriptor_table_BackupRes_2eproto_once,
      file_level_metadata_BackupRes_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace BackupRes
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::BackupRes::Backup* Arena::CreateMaybeMessage< ::BackupRes::Backup >(Arena* arena) {
  return Arena::CreateMessageInternal< ::BackupRes::Backup >(arena);
}
template<> PROTOBUF_NOINLINE ::BackupRes::Restore* Arena::CreateMaybeMessage< ::BackupRes::Restore >(Arena* arena) {
  return Arena::CreateMessageInternal< ::BackupRes::Restore >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
