// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Master.proto
#ifndef GRPC_Master_2eproto__INCLUDED
#define GRPC_Master_2eproto__INCLUDED

#include "Master.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace NX {

class Master final {
 public:
  static constexpr char const* service_full_name() {
    return "NX.Master";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status playbackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::EmptyMsg* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> AsyncplaybackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(AsyncplaybackStopedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> PrepareAsyncplaybackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(PrepareAsyncplaybackStopedRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void playbackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) = 0;
      virtual void playbackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* AsyncplaybackStopedRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* PrepareAsyncplaybackStopedRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status playbackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::EmptyMsg* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> AsyncplaybackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(AsyncplaybackStopedRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> PrepareAsyncplaybackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(PrepareAsyncplaybackStopedRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void playbackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) override;
      void playbackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* AsyncplaybackStopedRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* PrepareAsyncplaybackStopedRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_playbackStoped_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status playbackStoped(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_playbackStoped : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_playbackStoped() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_playbackStoped() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status playbackStoped(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestplaybackStoped(::grpc::ServerContext* context, ::NX::EmptyMsg* request, ::grpc::ServerAsyncResponseWriter< ::NX::EmptyMsg>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_playbackStoped<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_playbackStoped : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_playbackStoped() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::NX::EmptyMsg, ::NX::EmptyMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response) { return this->playbackStoped(context, request, response); }));}
    void SetMessageAllocatorFor_playbackStoped(
        ::grpc::MessageAllocator< ::NX::EmptyMsg, ::NX::EmptyMsg>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::NX::EmptyMsg, ::NX::EmptyMsg>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_playbackStoped() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status playbackStoped(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* playbackStoped(
      ::grpc::CallbackServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_playbackStoped<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_playbackStoped : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_playbackStoped() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_playbackStoped() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status playbackStoped(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_playbackStoped : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_playbackStoped() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_playbackStoped() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status playbackStoped(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestplaybackStoped(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_playbackStoped : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_playbackStoped() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->playbackStoped(context, request, response); }));
    }
    ~WithRawCallbackMethod_playbackStoped() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status playbackStoped(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* playbackStoped(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_playbackStoped : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_playbackStoped() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NX::EmptyMsg, ::NX::EmptyMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::NX::EmptyMsg, ::NX::EmptyMsg>* streamer) {
                       return this->StreamedplaybackStoped(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_playbackStoped() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status playbackStoped(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedplaybackStoped(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NX::EmptyMsg,::NX::EmptyMsg>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_playbackStoped<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_playbackStoped<Service > StreamedService;
};

}  // namespace NX


#endif  // GRPC_Master_2eproto__INCLUDED
