// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Master.proto

#include "Master.pb.h"
#include "Master.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace NX {

static const char* Master_method_names[] = {
  "/NX.Master/playbackStoped",
};

std::unique_ptr< Master::Stub> Master::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Master::Stub> stub(new Master::Stub(channel, options));
  return stub;
}

Master::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_playbackStoped_(Master_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Master::Stub::playbackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_playbackStoped_, context, request, response);
}

void Master::Stub::async::playbackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_playbackStoped_, context, request, response, std::move(f));
}

void Master::Stub::async::playbackStoped(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_playbackStoped_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::PrepareAsyncplaybackStopedRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_playbackStoped_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::AsyncplaybackStopedRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncplaybackStopedRaw(context, request, cq);
  result->StartCall();
  return result;
}

Master::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Master_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Master::Service, ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Master::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->playbackStoped(ctx, req, resp);
             }, this)));
}

Master::Service::~Service() {
}

::grpc::Status Master::Service::playbackStoped(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace NX

