// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Recorder.proto

#include "Recorder.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace NX {
}  // namespace NX
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Recorder_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Recorder_2eproto = nullptr;
const uint32_t TableStruct_Recorder_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Recorder_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016Recorder.proto\022\002NX\032\017NxMessage.proto2\211\021"
  "\n\010Recorder\022*\n\013connectTest\022\014.NX.EmptyMsg\032"
  "\013.NX.BoolMsg\"\000\022,\n\013setMasterId\022\r.NX.Strin"
  "gMsg\032\014.NX.EmptyMsg\"\000\0224\n\025isControllerConn"
  "ected\022\014.NX.EmptyMsg\032\013.NX.BoolMsg\"\000\022/\n\tin"
  "itBoard\022\020.NX.InitBoardMsg\032\016.NX.SignalsMs"
  "g\"\000\022/\n\017closeController\022\014.NX.EmptyMsg\032\014.N"
  "X.EmptyMsg\"\000\022-\n\017resetSampleRate\022\n.NX.Int"
  "Msg\032\014.NX.EmptyMsg\"\000\022\'\n\006getPID\022\014.NX.Empty"
  "Msg\032\r.NX.StringMsg\"\000\022,\n\013getDeviceID\022\014.NX"
  ".EmptyMsg\032\r.NX.StringMsg\"\000\022\'\n\006getVID\022\014.N"
  "X.EmptyMsg\032\r.NX.StringMsg\"\000\0228\n\020loadWavef"
  "ormData\022\021.NX.StringListMsg\032\017.NX.Waveform"
  "Msg\"\000\0224\n\023setOscillographMode\022\r.NX.OsMode"
  "Msg\032\014.NX.EmptyMsg\"\000\0224\n\023setSelectedWaveNa"
  "me\022\r.NX.StringMsg\032\014.NX.EmptyMsg\"\000\022B\n\023loa"
  "dSpectrogramData\022\014.NX.EmptyMsg\032\031.NX.Spec"
  "trogramSegmentMsg\"\0000\001\022+\n\rsetSignalInfo\022\n"
  ".NX.IntMsg\032\014.NX.EmptyMsg\"\000\0226\n\rsetSignalT"
  "ype\022\025.NX.SignalsMsgRequest\032\014.NX.EmptyMsg"
  "\"\000\022*\n\014setTimeScale\022\n.NX.IntMsg\032\014.NX.Empt"
  "yMsg\"\000\022(\n\010setNotch\022\014.NX.NotchMsg\032\014.NX.Em"
  "ptyMsg\"\000\022-\n\014setLowFilter\022\r.NX.FilterMsg\032"
  "\014.NX.EmptyMsg\"\000\022.\n\rsetHighFilter\022\r.NX.Fi"
  "lterMsg\032\014.NX.EmptyMsg\"\000\0225\n\026enableMeasure"
  "HeatScale\022\013.NX.BoolMsg\032\014.NX.EmptyMsg\"\000\022D"
  "\n\024setHeatScaleChannels\022\034.NX.HeatScaleCha"
  "nnelNamesMsg\032\014.NX.EmptyMsg\"\000\0226\n\rgetHeatS"
  "cales\022\014.NX.EmptyMsg\032\025.NX.HeatScaleRespon"
  "se\"\000\0223\n\016sendSetCommand\022\021.NX.SetCommandMs"
  "g\032\014.NX.EmptyMsg\"\000\022;\n\022sendExecuteCommand\022"
  "\025.NX.ExecuteCommandMsg\032\014.NX.EmptyMsg\"\000\022/"
  "\n\016setStoragePath\022\r.NX.StringMsg\032\014.NX.Emp"
  "tyMsg\"\000\0225\n\024setImpedanceFileName\022\r.NX.Str"
  "ingMsg\032\014.NX.EmptyMsg\"\000\022+\n\013startRecord\022\014."
  "NX.EmptyMsg\032\014.NX.EmptyMsg\"\000\022+\n\rrestartRe"
  "cord\022\n.NX.IntMsg\032\014.NX.EmptyMsg\"\000\022*\n\nstop"
  "Record\022\014.NX.EmptyMsg\032\014.NX.EmptyMsg\"\000\022>\n\030"
  "getDisplayListAmplifiers\022\r.NX.StringMsg\032"
  "\021.NX.StringListMsg\"\000\0228\n\022updateDisplayPar"
  "am\022\022.NX.DiplayParamMsg\032\014.NX.EmptyMsg\"\000\0229"
  "\n\022updateFilterParams\022\023.NX.FilterParamsMs"
  "g\032\014.NX.EmptyMsg\"\000\0229\n\020getImpedanceInfo\022\021."
  "NX.StringListMsg\032\020.NX.ImpedanceMsg\"\000\022\?\n\031"
  "getMeasureImpedanceStatus\022\014.NX.EmptyMsg\032"
  "\022.NX.ProgressStatus\"\000\022;\n\017getBufferStatus"
  "\022\014.NX.EmptyMsg\032\030.NX.BufferStatusResponse"
  "\"\000\0223\n\016jumpToPosition\022\021.NX.TargetTimeMsg\032"
  "\014.NX.EmptyMsg\"\000\0223\n\013startBackup\022\024.NX.Back"
  "upRestoreMsg\032\014.NX.EmptyMsg\"\000\022.\n\014startRes"
  "tore\022\016.NX.RestoreMsg\032\014.NX.EmptyMsg\"\000\022.\n\n"
  "exportData\022\021.NX.ExportDataMsg\032\013.NX.BoolM"
  "sg\"\000\022*\n\nstopExport\022\014.NX.EmptyMsg\032\014.NX.Em"
  "ptyMsg\"\000\022.\n\017isExportRunning\022\014.NX.EmptyMs"
  "g\032\013.NX.BoolMsg\"\000\022/\n\021getExportProgress\022\014."
  "NX.EmptyMsg\032\n.NX.IntMsg\"\000B\022\n\020io.grpc.rec"
  "orderb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Recorder_2eproto_deps[1] = {
  &::descriptor_table_NxMessage_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Recorder_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Recorder_2eproto = {
  false, false, 2253, descriptor_table_protodef_Recorder_2eproto, "Recorder.proto", 
  &descriptor_table_Recorder_2eproto_once, descriptor_table_Recorder_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_Recorder_2eproto::offsets,
  nullptr, file_level_enum_descriptors_Recorder_2eproto, file_level_service_descriptors_Recorder_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_Recorder_2eproto_getter() {
  return &descriptor_table_Recorder_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Recorder_2eproto(&descriptor_table_Recorder_2eproto);
namespace NX {

// @@protoc_insertion_point(namespace_scope)
}  // namespace NX
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
