// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: BackupRes.proto
#ifndef GRPC_BackupRes_2eproto__INCLUDED
#define GRPC_BackupRes_2eproto__INCLUDED

#include "BackupRes.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace BackupRes {

class BackupResService final {
 public:
  static constexpr char const* service_full_name() {
    return "BackupRes.BackupResService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status setBackup(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::BackupRes::Backup* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BackupRes::Backup>> AsyncsetBackup(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BackupRes::Backup>>(AsyncsetBackupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BackupRes::Backup>> PrepareAsyncsetBackup(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BackupRes::Backup>>(PrepareAsyncsetBackupRaw(context, request, cq));
    }
    virtual ::grpc::Status setRestore(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::BackupRes::Restore* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BackupRes::Restore>> AsyncsetRestore(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BackupRes::Restore>>(AsyncsetRestoreRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BackupRes::Restore>> PrepareAsyncsetRestore(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BackupRes::Restore>>(PrepareAsyncsetRestoreRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void setBackup(::grpc::ClientContext* context, const ::BackupRes::Backup* request, ::BackupRes::Backup* response, std::function<void(::grpc::Status)>) = 0;
      virtual void setBackup(::grpc::ClientContext* context, const ::BackupRes::Backup* request, ::BackupRes::Backup* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void setRestore(::grpc::ClientContext* context, const ::BackupRes::Restore* request, ::BackupRes::Restore* response, std::function<void(::grpc::Status)>) = 0;
      virtual void setRestore(::grpc::ClientContext* context, const ::BackupRes::Restore* request, ::BackupRes::Restore* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::BackupRes::Backup>* AsyncsetBackupRaw(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::BackupRes::Backup>* PrepareAsyncsetBackupRaw(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::BackupRes::Restore>* AsyncsetRestoreRaw(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::BackupRes::Restore>* PrepareAsyncsetRestoreRaw(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status setBackup(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::BackupRes::Backup* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BackupRes::Backup>> AsyncsetBackup(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BackupRes::Backup>>(AsyncsetBackupRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BackupRes::Backup>> PrepareAsyncsetBackup(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BackupRes::Backup>>(PrepareAsyncsetBackupRaw(context, request, cq));
    }
    ::grpc::Status setRestore(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::BackupRes::Restore* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BackupRes::Restore>> AsyncsetRestore(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BackupRes::Restore>>(AsyncsetRestoreRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BackupRes::Restore>> PrepareAsyncsetRestore(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BackupRes::Restore>>(PrepareAsyncsetRestoreRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void setBackup(::grpc::ClientContext* context, const ::BackupRes::Backup* request, ::BackupRes::Backup* response, std::function<void(::grpc::Status)>) override;
      void setBackup(::grpc::ClientContext* context, const ::BackupRes::Backup* request, ::BackupRes::Backup* response, ::grpc::ClientUnaryReactor* reactor) override;
      void setRestore(::grpc::ClientContext* context, const ::BackupRes::Restore* request, ::BackupRes::Restore* response, std::function<void(::grpc::Status)>) override;
      void setRestore(::grpc::ClientContext* context, const ::BackupRes::Restore* request, ::BackupRes::Restore* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::BackupRes::Backup>* AsyncsetBackupRaw(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::BackupRes::Backup>* PrepareAsyncsetBackupRaw(::grpc::ClientContext* context, const ::BackupRes::Backup& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::BackupRes::Restore>* AsyncsetRestoreRaw(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::BackupRes::Restore>* PrepareAsyncsetRestoreRaw(::grpc::ClientContext* context, const ::BackupRes::Restore& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_setBackup_;
    const ::grpc::internal::RpcMethod rpcmethod_setRestore_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status setBackup(::grpc::ServerContext* context, const ::BackupRes::Backup* request, ::BackupRes::Backup* response);
    virtual ::grpc::Status setRestore(::grpc::ServerContext* context, const ::BackupRes::Restore* request, ::BackupRes::Restore* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_setBackup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_setBackup() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_setBackup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setBackup(::grpc::ServerContext* /*context*/, const ::BackupRes::Backup* /*request*/, ::BackupRes::Backup* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetBackup(::grpc::ServerContext* context, ::BackupRes::Backup* request, ::grpc::ServerAsyncResponseWriter< ::BackupRes::Backup>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_setRestore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_setRestore() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_setRestore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setRestore(::grpc::ServerContext* /*context*/, const ::BackupRes::Restore* /*request*/, ::BackupRes::Restore* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetRestore(::grpc::ServerContext* context, ::BackupRes::Restore* request, ::grpc::ServerAsyncResponseWriter< ::BackupRes::Restore>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_setBackup<WithAsyncMethod_setRestore<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_setBackup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_setBackup() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::BackupRes::Backup, ::BackupRes::Backup>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::BackupRes::Backup* request, ::BackupRes::Backup* response) { return this->setBackup(context, request, response); }));}
    void SetMessageAllocatorFor_setBackup(
        ::grpc::MessageAllocator< ::BackupRes::Backup, ::BackupRes::Backup>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::BackupRes::Backup, ::BackupRes::Backup>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_setBackup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setBackup(::grpc::ServerContext* /*context*/, const ::BackupRes::Backup* /*request*/, ::BackupRes::Backup* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setBackup(
      ::grpc::CallbackServerContext* /*context*/, const ::BackupRes::Backup* /*request*/, ::BackupRes::Backup* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_setRestore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_setRestore() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::BackupRes::Restore, ::BackupRes::Restore>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::BackupRes::Restore* request, ::BackupRes::Restore* response) { return this->setRestore(context, request, response); }));}
    void SetMessageAllocatorFor_setRestore(
        ::grpc::MessageAllocator< ::BackupRes::Restore, ::BackupRes::Restore>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::BackupRes::Restore, ::BackupRes::Restore>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_setRestore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setRestore(::grpc::ServerContext* /*context*/, const ::BackupRes::Restore* /*request*/, ::BackupRes::Restore* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setRestore(
      ::grpc::CallbackServerContext* /*context*/, const ::BackupRes::Restore* /*request*/, ::BackupRes::Restore* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_setBackup<WithCallbackMethod_setRestore<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_setBackup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_setBackup() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_setBackup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setBackup(::grpc::ServerContext* /*context*/, const ::BackupRes::Backup* /*request*/, ::BackupRes::Backup* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_setRestore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_setRestore() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_setRestore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setRestore(::grpc::ServerContext* /*context*/, const ::BackupRes::Restore* /*request*/, ::BackupRes::Restore* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_setBackup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_setBackup() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_setBackup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setBackup(::grpc::ServerContext* /*context*/, const ::BackupRes::Backup* /*request*/, ::BackupRes::Backup* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetBackup(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_setRestore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_setRestore() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_setRestore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setRestore(::grpc::ServerContext* /*context*/, const ::BackupRes::Restore* /*request*/, ::BackupRes::Restore* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetRestore(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_setBackup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_setBackup() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->setBackup(context, request, response); }));
    }
    ~WithRawCallbackMethod_setBackup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setBackup(::grpc::ServerContext* /*context*/, const ::BackupRes::Backup* /*request*/, ::BackupRes::Backup* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setBackup(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_setRestore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_setRestore() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->setRestore(context, request, response); }));
    }
    ~WithRawCallbackMethod_setRestore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setRestore(::grpc::ServerContext* /*context*/, const ::BackupRes::Restore* /*request*/, ::BackupRes::Restore* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setRestore(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_setBackup : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_setBackup() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::BackupRes::Backup, ::BackupRes::Backup>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::BackupRes::Backup, ::BackupRes::Backup>* streamer) {
                       return this->StreamedsetBackup(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_setBackup() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status setBackup(::grpc::ServerContext* /*context*/, const ::BackupRes::Backup* /*request*/, ::BackupRes::Backup* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsetBackup(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::BackupRes::Backup,::BackupRes::Backup>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_setRestore : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_setRestore() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::BackupRes::Restore, ::BackupRes::Restore>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::BackupRes::Restore, ::BackupRes::Restore>* streamer) {
                       return this->StreamedsetRestore(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_setRestore() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status setRestore(::grpc::ServerContext* /*context*/, const ::BackupRes::Restore* /*request*/, ::BackupRes::Restore* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsetRestore(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::BackupRes::Restore,::BackupRes::Restore>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_setBackup<WithStreamedUnaryMethod_setRestore<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_setBackup<WithStreamedUnaryMethod_setRestore<Service > > StreamedService;
};

}  // namespace BackupRes


#endif  // GRPC_BackupRes_2eproto__INCLUDED
