// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Master.proto
#ifndef GRPC_Master_2eproto__INCLUDED
#define GRPC_Master_2eproto__INCLUDED

#include "Master.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace NX {

class Master final {
 public:
  static constexpr char const* service_full_name() {
    return "NX.Master";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status connectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::BoolMsg* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::BoolMsg>> AsyncconnectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::BoolMsg>>(AsyncconnectTestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::BoolMsg>> PrepareAsyncconnectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::BoolMsg>>(PrepareAsyncconnectTestRaw(context, request, cq));
    }
    virtual ::grpc::Status updateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::EmptyMsg* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> AsyncupdateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(AsyncupdateForRescanRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> PrepareAsyncupdateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(PrepareAsyncupdateForRescanRaw(context, request, cq));
    }
    virtual ::grpc::Status updatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::NX::EmptyMsg* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> AsyncupdatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(AsyncupdatePortSelectionBoxesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> PrepareAsyncupdatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(PrepareAsyncupdatePortSelectionBoxesRaw(context, request, cq));
    }
    virtual ::grpc::Status reset(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::EmptyMsg* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> Asyncreset(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(AsyncresetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> PrepareAsyncreset(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(PrepareAsyncresetRaw(context, request, cq));
    }
    virtual ::grpc::Status loadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::YScaleUsedMsg* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::YScaleUsedMsg>> AsyncloadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::YScaleUsedMsg>>(AsyncloadWaveformDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::YScaleUsedMsg>> PrepareAsyncloadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::YScaleUsedMsg>>(PrepareAsyncloadWaveformDataRaw(context, request, cq));
    }
    virtual ::grpc::Status updatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::NX::EmptyMsg* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> AsyncupdatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(AsyncupdatePluginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> PrepareAsyncupdatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(PrepareAsyncupdatePluginRaw(context, request, cq));
    }
    virtual ::grpc::Status loadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::NX::YScaleUsedMsg* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::YScaleUsedMsg>> AsyncloadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::YScaleUsedMsg>>(AsyncloadWaveformDataFromMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::YScaleUsedMsg>> PrepareAsyncloadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::YScaleUsedMsg>>(PrepareAsyncloadWaveformDataFromMemoryRaw(context, request, cq));
    }
    virtual ::grpc::Status setSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::NX::EmptyMsg* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> AsyncsetSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(AsyncsetSaveStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> PrepareAsyncsetSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(PrepareAsyncsetSaveStateRaw(context, request, cq));
    }
    virtual ::grpc::Status setRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::NX::EmptyMsg* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> AsyncsetRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(AsyncsetRestoreStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>> PrepareAsyncsetRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>>(PrepareAsyncsetRestoreStateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void connectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::BoolMsg* response, std::function<void(::grpc::Status)>) = 0;
      virtual void connectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::BoolMsg* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void updateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) = 0;
      virtual void updateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void updatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) = 0;
      virtual void updatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void reset(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) = 0;
      virtual void reset(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void loadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::YScaleUsedMsg* response, std::function<void(::grpc::Status)>) = 0;
      virtual void loadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::YScaleUsedMsg* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void updatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) = 0;
      virtual void updatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void loadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg* request, ::NX::YScaleUsedMsg* response, std::function<void(::grpc::Status)>) = 0;
      virtual void loadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg* request, ::NX::YScaleUsedMsg* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void setSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) = 0;
      virtual void setSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void setRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) = 0;
      virtual void setRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::BoolMsg>* AsyncconnectTestRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::BoolMsg>* PrepareAsyncconnectTestRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* AsyncupdateForRescanRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* PrepareAsyncupdateForRescanRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* AsyncupdatePortSelectionBoxesRaw(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* PrepareAsyncupdatePortSelectionBoxesRaw(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* AsyncresetRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* PrepareAsyncresetRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::YScaleUsedMsg>* AsyncloadWaveformDataRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::YScaleUsedMsg>* PrepareAsyncloadWaveformDataRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* AsyncupdatePluginRaw(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* PrepareAsyncupdatePluginRaw(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::YScaleUsedMsg>* AsyncloadWaveformDataFromMemoryRaw(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::YScaleUsedMsg>* PrepareAsyncloadWaveformDataFromMemoryRaw(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* AsyncsetSaveStateRaw(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* PrepareAsyncsetSaveStateRaw(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* AsyncsetRestoreStateRaw(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NX::EmptyMsg>* PrepareAsyncsetRestoreStateRaw(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status connectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::BoolMsg* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::BoolMsg>> AsyncconnectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::BoolMsg>>(AsyncconnectTestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::BoolMsg>> PrepareAsyncconnectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::BoolMsg>>(PrepareAsyncconnectTestRaw(context, request, cq));
    }
    ::grpc::Status updateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::EmptyMsg* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> AsyncupdateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(AsyncupdateForRescanRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> PrepareAsyncupdateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(PrepareAsyncupdateForRescanRaw(context, request, cq));
    }
    ::grpc::Status updatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::NX::EmptyMsg* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> AsyncupdatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(AsyncupdatePortSelectionBoxesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> PrepareAsyncupdatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(PrepareAsyncupdatePortSelectionBoxesRaw(context, request, cq));
    }
    ::grpc::Status reset(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::EmptyMsg* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> Asyncreset(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(AsyncresetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> PrepareAsyncreset(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(PrepareAsyncresetRaw(context, request, cq));
    }
    ::grpc::Status loadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::YScaleUsedMsg* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>> AsyncloadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>>(AsyncloadWaveformDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>> PrepareAsyncloadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>>(PrepareAsyncloadWaveformDataRaw(context, request, cq));
    }
    ::grpc::Status updatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::NX::EmptyMsg* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> AsyncupdatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(AsyncupdatePluginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> PrepareAsyncupdatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(PrepareAsyncupdatePluginRaw(context, request, cq));
    }
    ::grpc::Status loadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::NX::YScaleUsedMsg* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>> AsyncloadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>>(AsyncloadWaveformDataFromMemoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>> PrepareAsyncloadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>>(PrepareAsyncloadWaveformDataFromMemoryRaw(context, request, cq));
    }
    ::grpc::Status setSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::NX::EmptyMsg* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> AsyncsetSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(AsyncsetSaveStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> PrepareAsyncsetSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(PrepareAsyncsetSaveStateRaw(context, request, cq));
    }
    ::grpc::Status setRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::NX::EmptyMsg* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> AsyncsetRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(AsyncsetRestoreStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>> PrepareAsyncsetRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>>(PrepareAsyncsetRestoreStateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void connectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::BoolMsg* response, std::function<void(::grpc::Status)>) override;
      void connectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::BoolMsg* response, ::grpc::ClientUnaryReactor* reactor) override;
      void updateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) override;
      void updateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) override;
      void updatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) override;
      void updatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) override;
      void reset(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) override;
      void reset(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) override;
      void loadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::YScaleUsedMsg* response, std::function<void(::grpc::Status)>) override;
      void loadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::YScaleUsedMsg* response, ::grpc::ClientUnaryReactor* reactor) override;
      void updatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) override;
      void updatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) override;
      void loadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg* request, ::NX::YScaleUsedMsg* response, std::function<void(::grpc::Status)>) override;
      void loadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg* request, ::NX::YScaleUsedMsg* response, ::grpc::ClientUnaryReactor* reactor) override;
      void setSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) override;
      void setSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) override;
      void setRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)>) override;
      void setRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::NX::BoolMsg>* AsyncconnectTestRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::BoolMsg>* PrepareAsyncconnectTestRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* AsyncupdateForRescanRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* PrepareAsyncupdateForRescanRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* AsyncupdatePortSelectionBoxesRaw(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* PrepareAsyncupdatePortSelectionBoxesRaw(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* AsyncresetRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* PrepareAsyncresetRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>* AsyncloadWaveformDataRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>* PrepareAsyncloadWaveformDataRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* AsyncupdatePluginRaw(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* PrepareAsyncupdatePluginRaw(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>* AsyncloadWaveformDataFromMemoryRaw(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>* PrepareAsyncloadWaveformDataFromMemoryRaw(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* AsyncsetSaveStateRaw(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* PrepareAsyncsetSaveStateRaw(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* AsyncsetRestoreStateRaw(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* PrepareAsyncsetRestoreStateRaw(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_connectTest_;
    const ::grpc::internal::RpcMethod rpcmethod_updateForRescan_;
    const ::grpc::internal::RpcMethod rpcmethod_updatePortSelectionBoxes_;
    const ::grpc::internal::RpcMethod rpcmethod_reset_;
    const ::grpc::internal::RpcMethod rpcmethod_loadWaveformData_;
    const ::grpc::internal::RpcMethod rpcmethod_updatePlugin_;
    const ::grpc::internal::RpcMethod rpcmethod_loadWaveformDataFromMemory_;
    const ::grpc::internal::RpcMethod rpcmethod_setSaveState_;
    const ::grpc::internal::RpcMethod rpcmethod_setRestoreState_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status connectTest(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::BoolMsg* response);
    virtual ::grpc::Status updateForRescan(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response);
    virtual ::grpc::Status updatePortSelectionBoxes(::grpc::ServerContext* context, const ::NX::BoolMsg* request, ::NX::EmptyMsg* response);
    virtual ::grpc::Status reset(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response);
    virtual ::grpc::Status loadWaveformData(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::YScaleUsedMsg* response);
    virtual ::grpc::Status updatePlugin(::grpc::ServerContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response);
    virtual ::grpc::Status loadWaveformDataFromMemory(::grpc::ServerContext* context, const ::NX::LoadWaveformDataFromMemoryMsg* request, ::NX::YScaleUsedMsg* response);
    virtual ::grpc::Status setSaveState(::grpc::ServerContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response);
    virtual ::grpc::Status setRestoreState(::grpc::ServerContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_connectTest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_connectTest() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_connectTest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connectTest(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::BoolMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestconnectTest(::grpc::ServerContext* context, ::NX::EmptyMsg* request, ::grpc::ServerAsyncResponseWriter< ::NX::BoolMsg>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_updateForRescan : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_updateForRescan() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_updateForRescan() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updateForRescan(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestupdateForRescan(::grpc::ServerContext* context, ::NX::EmptyMsg* request, ::grpc::ServerAsyncResponseWriter< ::NX::EmptyMsg>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_updatePortSelectionBoxes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_updatePortSelectionBoxes() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_updatePortSelectionBoxes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updatePortSelectionBoxes(::grpc::ServerContext* /*context*/, const ::NX::BoolMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestupdatePortSelectionBoxes(::grpc::ServerContext* context, ::NX::BoolMsg* request, ::grpc::ServerAsyncResponseWriter< ::NX::EmptyMsg>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_reset() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status reset(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestreset(::grpc::ServerContext* context, ::NX::EmptyMsg* request, ::grpc::ServerAsyncResponseWriter< ::NX::EmptyMsg>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_loadWaveformData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_loadWaveformData() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_loadWaveformData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status loadWaveformData(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestloadWaveformData(::grpc::ServerContext* context, ::NX::EmptyMsg* request, ::grpc::ServerAsyncResponseWriter< ::NX::YScaleUsedMsg>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_updatePlugin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_updatePlugin() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_updatePlugin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updatePlugin(::grpc::ServerContext* /*context*/, const ::NX::SampleMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestupdatePlugin(::grpc::ServerContext* context, ::NX::SampleMsg* request, ::grpc::ServerAsyncResponseWriter< ::NX::EmptyMsg>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_loadWaveformDataFromMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_loadWaveformDataFromMemory() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_loadWaveformDataFromMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status loadWaveformDataFromMemory(::grpc::ServerContext* /*context*/, const ::NX::LoadWaveformDataFromMemoryMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestloadWaveformDataFromMemory(::grpc::ServerContext* context, ::NX::LoadWaveformDataFromMemoryMsg* request, ::grpc::ServerAsyncResponseWriter< ::NX::YScaleUsedMsg>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_setSaveState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_setSaveState() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_setSaveState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setSaveState(::grpc::ServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetSaveState(::grpc::ServerContext* context, ::NX::DisplayStateMsg* request, ::grpc::ServerAsyncResponseWriter< ::NX::EmptyMsg>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_setRestoreState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_setRestoreState() {
      ::grpc::Service::MarkMethodAsync(8);
    }
    ~WithAsyncMethod_setRestoreState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setRestoreState(::grpc::ServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetRestoreState(::grpc::ServerContext* context, ::NX::DisplayStateMsg* request, ::grpc::ServerAsyncResponseWriter< ::NX::EmptyMsg>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(8, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_connectTest<WithAsyncMethod_updateForRescan<WithAsyncMethod_updatePortSelectionBoxes<WithAsyncMethod_reset<WithAsyncMethod_loadWaveformData<WithAsyncMethod_updatePlugin<WithAsyncMethod_loadWaveformDataFromMemory<WithAsyncMethod_setSaveState<WithAsyncMethod_setRestoreState<Service > > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_connectTest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_connectTest() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::NX::EmptyMsg, ::NX::BoolMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::NX::EmptyMsg* request, ::NX::BoolMsg* response) { return this->connectTest(context, request, response); }));}
    void SetMessageAllocatorFor_connectTest(
        ::grpc::MessageAllocator< ::NX::EmptyMsg, ::NX::BoolMsg>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::NX::EmptyMsg, ::NX::BoolMsg>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_connectTest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connectTest(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::BoolMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* connectTest(
      ::grpc::CallbackServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::BoolMsg* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_updateForRescan : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_updateForRescan() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::NX::EmptyMsg, ::NX::EmptyMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response) { return this->updateForRescan(context, request, response); }));}
    void SetMessageAllocatorFor_updateForRescan(
        ::grpc::MessageAllocator< ::NX::EmptyMsg, ::NX::EmptyMsg>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::NX::EmptyMsg, ::NX::EmptyMsg>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_updateForRescan() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updateForRescan(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* updateForRescan(
      ::grpc::CallbackServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_updatePortSelectionBoxes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_updatePortSelectionBoxes() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::NX::BoolMsg, ::NX::EmptyMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::NX::BoolMsg* request, ::NX::EmptyMsg* response) { return this->updatePortSelectionBoxes(context, request, response); }));}
    void SetMessageAllocatorFor_updatePortSelectionBoxes(
        ::grpc::MessageAllocator< ::NX::BoolMsg, ::NX::EmptyMsg>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::NX::BoolMsg, ::NX::EmptyMsg>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_updatePortSelectionBoxes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updatePortSelectionBoxes(::grpc::ServerContext* /*context*/, const ::NX::BoolMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* updatePortSelectionBoxes(
      ::grpc::CallbackServerContext* /*context*/, const ::NX::BoolMsg* /*request*/, ::NX::EmptyMsg* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_reset() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::NX::EmptyMsg, ::NX::EmptyMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response) { return this->reset(context, request, response); }));}
    void SetMessageAllocatorFor_reset(
        ::grpc::MessageAllocator< ::NX::EmptyMsg, ::NX::EmptyMsg>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::NX::EmptyMsg, ::NX::EmptyMsg>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status reset(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* reset(
      ::grpc::CallbackServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_loadWaveformData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_loadWaveformData() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::NX::EmptyMsg, ::NX::YScaleUsedMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::NX::EmptyMsg* request, ::NX::YScaleUsedMsg* response) { return this->loadWaveformData(context, request, response); }));}
    void SetMessageAllocatorFor_loadWaveformData(
        ::grpc::MessageAllocator< ::NX::EmptyMsg, ::NX::YScaleUsedMsg>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::NX::EmptyMsg, ::NX::YScaleUsedMsg>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_loadWaveformData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status loadWaveformData(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* loadWaveformData(
      ::grpc::CallbackServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_updatePlugin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_updatePlugin() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::NX::SampleMsg, ::NX::EmptyMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response) { return this->updatePlugin(context, request, response); }));}
    void SetMessageAllocatorFor_updatePlugin(
        ::grpc::MessageAllocator< ::NX::SampleMsg, ::NX::EmptyMsg>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::NX::SampleMsg, ::NX::EmptyMsg>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_updatePlugin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updatePlugin(::grpc::ServerContext* /*context*/, const ::NX::SampleMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* updatePlugin(
      ::grpc::CallbackServerContext* /*context*/, const ::NX::SampleMsg* /*request*/, ::NX::EmptyMsg* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_loadWaveformDataFromMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_loadWaveformDataFromMemory() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::NX::LoadWaveformDataFromMemoryMsg, ::NX::YScaleUsedMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::NX::LoadWaveformDataFromMemoryMsg* request, ::NX::YScaleUsedMsg* response) { return this->loadWaveformDataFromMemory(context, request, response); }));}
    void SetMessageAllocatorFor_loadWaveformDataFromMemory(
        ::grpc::MessageAllocator< ::NX::LoadWaveformDataFromMemoryMsg, ::NX::YScaleUsedMsg>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(6);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::NX::LoadWaveformDataFromMemoryMsg, ::NX::YScaleUsedMsg>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_loadWaveformDataFromMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status loadWaveformDataFromMemory(::grpc::ServerContext* /*context*/, const ::NX::LoadWaveformDataFromMemoryMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* loadWaveformDataFromMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::NX::LoadWaveformDataFromMemoryMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_setSaveState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_setSaveState() {
      ::grpc::Service::MarkMethodCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::NX::DisplayStateMsg, ::NX::EmptyMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response) { return this->setSaveState(context, request, response); }));}
    void SetMessageAllocatorFor_setSaveState(
        ::grpc::MessageAllocator< ::NX::DisplayStateMsg, ::NX::EmptyMsg>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(7);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::NX::DisplayStateMsg, ::NX::EmptyMsg>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_setSaveState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setSaveState(::grpc::ServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setSaveState(
      ::grpc::CallbackServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_setRestoreState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_setRestoreState() {
      ::grpc::Service::MarkMethodCallback(8,
          new ::grpc::internal::CallbackUnaryHandler< ::NX::DisplayStateMsg, ::NX::EmptyMsg>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response) { return this->setRestoreState(context, request, response); }));}
    void SetMessageAllocatorFor_setRestoreState(
        ::grpc::MessageAllocator< ::NX::DisplayStateMsg, ::NX::EmptyMsg>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(8);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::NX::DisplayStateMsg, ::NX::EmptyMsg>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_setRestoreState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setRestoreState(::grpc::ServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setRestoreState(
      ::grpc::CallbackServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_connectTest<WithCallbackMethod_updateForRescan<WithCallbackMethod_updatePortSelectionBoxes<WithCallbackMethod_reset<WithCallbackMethod_loadWaveformData<WithCallbackMethod_updatePlugin<WithCallbackMethod_loadWaveformDataFromMemory<WithCallbackMethod_setSaveState<WithCallbackMethod_setRestoreState<Service > > > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_connectTest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_connectTest() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_connectTest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connectTest(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::BoolMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_updateForRescan : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_updateForRescan() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_updateForRescan() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updateForRescan(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_updatePortSelectionBoxes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_updatePortSelectionBoxes() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_updatePortSelectionBoxes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updatePortSelectionBoxes(::grpc::ServerContext* /*context*/, const ::NX::BoolMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_reset() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status reset(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_loadWaveformData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_loadWaveformData() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_loadWaveformData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status loadWaveformData(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_updatePlugin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_updatePlugin() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_updatePlugin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updatePlugin(::grpc::ServerContext* /*context*/, const ::NX::SampleMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_loadWaveformDataFromMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_loadWaveformDataFromMemory() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_loadWaveformDataFromMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status loadWaveformDataFromMemory(::grpc::ServerContext* /*context*/, const ::NX::LoadWaveformDataFromMemoryMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_setSaveState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_setSaveState() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_setSaveState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setSaveState(::grpc::ServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_setRestoreState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_setRestoreState() {
      ::grpc::Service::MarkMethodGeneric(8);
    }
    ~WithGenericMethod_setRestoreState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setRestoreState(::grpc::ServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_connectTest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_connectTest() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_connectTest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connectTest(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::BoolMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestconnectTest(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_updateForRescan : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_updateForRescan() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_updateForRescan() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updateForRescan(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestupdateForRescan(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_updatePortSelectionBoxes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_updatePortSelectionBoxes() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_updatePortSelectionBoxes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updatePortSelectionBoxes(::grpc::ServerContext* /*context*/, const ::NX::BoolMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestupdatePortSelectionBoxes(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_reset() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status reset(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestreset(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_loadWaveformData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_loadWaveformData() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_loadWaveformData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status loadWaveformData(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestloadWaveformData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_updatePlugin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_updatePlugin() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_updatePlugin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updatePlugin(::grpc::ServerContext* /*context*/, const ::NX::SampleMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestupdatePlugin(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_loadWaveformDataFromMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_loadWaveformDataFromMemory() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_loadWaveformDataFromMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status loadWaveformDataFromMemory(::grpc::ServerContext* /*context*/, const ::NX::LoadWaveformDataFromMemoryMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestloadWaveformDataFromMemory(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_setSaveState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_setSaveState() {
      ::grpc::Service::MarkMethodRaw(7);
    }
    ~WithRawMethod_setSaveState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setSaveState(::grpc::ServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetSaveState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_setRestoreState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_setRestoreState() {
      ::grpc::Service::MarkMethodRaw(8);
    }
    ~WithRawMethod_setRestoreState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setRestoreState(::grpc::ServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetRestoreState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(8, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_connectTest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_connectTest() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->connectTest(context, request, response); }));
    }
    ~WithRawCallbackMethod_connectTest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status connectTest(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::BoolMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* connectTest(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_updateForRescan : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_updateForRescan() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->updateForRescan(context, request, response); }));
    }
    ~WithRawCallbackMethod_updateForRescan() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updateForRescan(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* updateForRescan(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_updatePortSelectionBoxes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_updatePortSelectionBoxes() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->updatePortSelectionBoxes(context, request, response); }));
    }
    ~WithRawCallbackMethod_updatePortSelectionBoxes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updatePortSelectionBoxes(::grpc::ServerContext* /*context*/, const ::NX::BoolMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* updatePortSelectionBoxes(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_reset() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->reset(context, request, response); }));
    }
    ~WithRawCallbackMethod_reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status reset(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* reset(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_loadWaveformData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_loadWaveformData() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->loadWaveformData(context, request, response); }));
    }
    ~WithRawCallbackMethod_loadWaveformData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status loadWaveformData(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* loadWaveformData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_updatePlugin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_updatePlugin() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->updatePlugin(context, request, response); }));
    }
    ~WithRawCallbackMethod_updatePlugin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status updatePlugin(::grpc::ServerContext* /*context*/, const ::NX::SampleMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* updatePlugin(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_loadWaveformDataFromMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_loadWaveformDataFromMemory() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->loadWaveformDataFromMemory(context, request, response); }));
    }
    ~WithRawCallbackMethod_loadWaveformDataFromMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status loadWaveformDataFromMemory(::grpc::ServerContext* /*context*/, const ::NX::LoadWaveformDataFromMemoryMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* loadWaveformDataFromMemory(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_setSaveState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_setSaveState() {
      ::grpc::Service::MarkMethodRawCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->setSaveState(context, request, response); }));
    }
    ~WithRawCallbackMethod_setSaveState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setSaveState(::grpc::ServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setSaveState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_setRestoreState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_setRestoreState() {
      ::grpc::Service::MarkMethodRawCallback(8,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->setRestoreState(context, request, response); }));
    }
    ~WithRawCallbackMethod_setRestoreState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setRestoreState(::grpc::ServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* setRestoreState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_connectTest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_connectTest() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NX::EmptyMsg, ::NX::BoolMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::NX::EmptyMsg, ::NX::BoolMsg>* streamer) {
                       return this->StreamedconnectTest(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_connectTest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status connectTest(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::BoolMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedconnectTest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NX::EmptyMsg,::NX::BoolMsg>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_updateForRescan : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_updateForRescan() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NX::EmptyMsg, ::NX::EmptyMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::NX::EmptyMsg, ::NX::EmptyMsg>* streamer) {
                       return this->StreamedupdateForRescan(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_updateForRescan() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status updateForRescan(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedupdateForRescan(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NX::EmptyMsg,::NX::EmptyMsg>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_updatePortSelectionBoxes : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_updatePortSelectionBoxes() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NX::BoolMsg, ::NX::EmptyMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::NX::BoolMsg, ::NX::EmptyMsg>* streamer) {
                       return this->StreamedupdatePortSelectionBoxes(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_updatePortSelectionBoxes() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status updatePortSelectionBoxes(::grpc::ServerContext* /*context*/, const ::NX::BoolMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedupdatePortSelectionBoxes(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NX::BoolMsg,::NX::EmptyMsg>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_reset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_reset() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NX::EmptyMsg, ::NX::EmptyMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::NX::EmptyMsg, ::NX::EmptyMsg>* streamer) {
                       return this->Streamedreset(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_reset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status reset(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedreset(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NX::EmptyMsg,::NX::EmptyMsg>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_loadWaveformData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_loadWaveformData() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NX::EmptyMsg, ::NX::YScaleUsedMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::NX::EmptyMsg, ::NX::YScaleUsedMsg>* streamer) {
                       return this->StreamedloadWaveformData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_loadWaveformData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status loadWaveformData(::grpc::ServerContext* /*context*/, const ::NX::EmptyMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedloadWaveformData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NX::EmptyMsg,::NX::YScaleUsedMsg>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_updatePlugin : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_updatePlugin() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NX::SampleMsg, ::NX::EmptyMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::NX::SampleMsg, ::NX::EmptyMsg>* streamer) {
                       return this->StreamedupdatePlugin(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_updatePlugin() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status updatePlugin(::grpc::ServerContext* /*context*/, const ::NX::SampleMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedupdatePlugin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NX::SampleMsg,::NX::EmptyMsg>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_loadWaveformDataFromMemory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_loadWaveformDataFromMemory() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NX::LoadWaveformDataFromMemoryMsg, ::NX::YScaleUsedMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::NX::LoadWaveformDataFromMemoryMsg, ::NX::YScaleUsedMsg>* streamer) {
                       return this->StreamedloadWaveformDataFromMemory(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_loadWaveformDataFromMemory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status loadWaveformDataFromMemory(::grpc::ServerContext* /*context*/, const ::NX::LoadWaveformDataFromMemoryMsg* /*request*/, ::NX::YScaleUsedMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedloadWaveformDataFromMemory(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NX::LoadWaveformDataFromMemoryMsg,::NX::YScaleUsedMsg>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_setSaveState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_setSaveState() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NX::DisplayStateMsg, ::NX::EmptyMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::NX::DisplayStateMsg, ::NX::EmptyMsg>* streamer) {
                       return this->StreamedsetSaveState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_setSaveState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status setSaveState(::grpc::ServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsetSaveState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NX::DisplayStateMsg,::NX::EmptyMsg>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_setRestoreState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_setRestoreState() {
      ::grpc::Service::MarkMethodStreamed(8,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NX::DisplayStateMsg, ::NX::EmptyMsg>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::NX::DisplayStateMsg, ::NX::EmptyMsg>* streamer) {
                       return this->StreamedsetRestoreState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_setRestoreState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status setRestoreState(::grpc::ServerContext* /*context*/, const ::NX::DisplayStateMsg* /*request*/, ::NX::EmptyMsg* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsetRestoreState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NX::DisplayStateMsg,::NX::EmptyMsg>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_connectTest<WithStreamedUnaryMethod_updateForRescan<WithStreamedUnaryMethod_updatePortSelectionBoxes<WithStreamedUnaryMethod_reset<WithStreamedUnaryMethod_loadWaveformData<WithStreamedUnaryMethod_updatePlugin<WithStreamedUnaryMethod_loadWaveformDataFromMemory<WithStreamedUnaryMethod_setSaveState<WithStreamedUnaryMethod_setRestoreState<Service > > > > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_connectTest<WithStreamedUnaryMethod_updateForRescan<WithStreamedUnaryMethod_updatePortSelectionBoxes<WithStreamedUnaryMethod_reset<WithStreamedUnaryMethod_loadWaveformData<WithStreamedUnaryMethod_updatePlugin<WithStreamedUnaryMethod_loadWaveformDataFromMemory<WithStreamedUnaryMethod_setSaveState<WithStreamedUnaryMethod_setRestoreState<Service > > > > > > > > > StreamedService;
};

}  // namespace NX


#endif  // GRPC_Master_2eproto__INCLUDED
