// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Master.proto

#include "Master.pb.h"
#include "Master.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace NX {

static const char* Master_method_names[] = {
  "/NX.Master/connectTest",
  "/NX.Master/updateForRescan",
  "/NX.Master/updatePortSelectionBoxes",
  "/NX.Master/reset",
  "/NX.Master/loadWaveformData",
  "/NX.Master/updatePlugin",
  "/NX.Master/loadWaveformDataFromMemory",
  "/NX.Master/setSaveState",
  "/NX.Master/setRestoreState",
};

std::unique_ptr< Master::Stub> Master::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Master::Stub> stub(new Master::Stub(channel, options));
  return stub;
}

Master::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_connectTest_(Master_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_updateForRescan_(Master_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_updatePortSelectionBoxes_(Master_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_reset_(Master_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_loadWaveformData_(Master_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_updatePlugin_(Master_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_loadWaveformDataFromMemory_(Master_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setSaveState_(Master_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setRestoreState_(Master_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Master::Stub::connectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::BoolMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::BoolMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_connectTest_, context, request, response);
}

void Master::Stub::async::connectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::BoolMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::BoolMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_connectTest_, context, request, response, std::move(f));
}

void Master::Stub::async::connectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::BoolMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_connectTest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::BoolMsg>* Master::Stub::PrepareAsyncconnectTestRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::BoolMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_connectTest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::BoolMsg>* Master::Stub::AsyncconnectTestRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncconnectTestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Master::Stub::updateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_updateForRescan_, context, request, response);
}

void Master::Stub::async::updateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_updateForRescan_, context, request, response, std::move(f));
}

void Master::Stub::async::updateForRescan(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_updateForRescan_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::PrepareAsyncupdateForRescanRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_updateForRescan_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::AsyncupdateForRescanRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncupdateForRescanRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Master::Stub::updatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::BoolMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_updatePortSelectionBoxes_, context, request, response);
}

void Master::Stub::async::updatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::BoolMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_updatePortSelectionBoxes_, context, request, response, std::move(f));
}

void Master::Stub::async::updatePortSelectionBoxes(::grpc::ClientContext* context, const ::NX::BoolMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_updatePortSelectionBoxes_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::PrepareAsyncupdatePortSelectionBoxesRaw(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::BoolMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_updatePortSelectionBoxes_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::AsyncupdatePortSelectionBoxesRaw(::grpc::ClientContext* context, const ::NX::BoolMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncupdatePortSelectionBoxesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Master::Stub::reset(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_reset_, context, request, response);
}

void Master::Stub::async::reset(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_reset_, context, request, response, std::move(f));
}

void Master::Stub::async::reset(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_reset_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::PrepareAsyncresetRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_reset_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::AsyncresetRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncresetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Master::Stub::loadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::YScaleUsedMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::YScaleUsedMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_loadWaveformData_, context, request, response);
}

void Master::Stub::async::loadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::YScaleUsedMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::YScaleUsedMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_loadWaveformData_, context, request, response, std::move(f));
}

void Master::Stub::async::loadWaveformData(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::YScaleUsedMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_loadWaveformData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>* Master::Stub::PrepareAsyncloadWaveformDataRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::YScaleUsedMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_loadWaveformData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>* Master::Stub::AsyncloadWaveformDataRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncloadWaveformDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Master::Stub::updatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::SampleMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_updatePlugin_, context, request, response);
}

void Master::Stub::async::updatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::SampleMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_updatePlugin_, context, request, response, std::move(f));
}

void Master::Stub::async::updatePlugin(::grpc::ClientContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_updatePlugin_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::PrepareAsyncupdatePluginRaw(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::SampleMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_updatePlugin_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::AsyncupdatePluginRaw(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncupdatePluginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Master::Stub::loadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::NX::YScaleUsedMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::LoadWaveformDataFromMemoryMsg, ::NX::YScaleUsedMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_loadWaveformDataFromMemory_, context, request, response);
}

void Master::Stub::async::loadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg* request, ::NX::YScaleUsedMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::LoadWaveformDataFromMemoryMsg, ::NX::YScaleUsedMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_loadWaveformDataFromMemory_, context, request, response, std::move(f));
}

void Master::Stub::async::loadWaveformDataFromMemory(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg* request, ::NX::YScaleUsedMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_loadWaveformDataFromMemory_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>* Master::Stub::PrepareAsyncloadWaveformDataFromMemoryRaw(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::YScaleUsedMsg, ::NX::LoadWaveformDataFromMemoryMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_loadWaveformDataFromMemory_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::YScaleUsedMsg>* Master::Stub::AsyncloadWaveformDataFromMemoryRaw(::grpc::ClientContext* context, const ::NX::LoadWaveformDataFromMemoryMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncloadWaveformDataFromMemoryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Master::Stub::setSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::DisplayStateMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setSaveState_, context, request, response);
}

void Master::Stub::async::setSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::DisplayStateMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setSaveState_, context, request, response, std::move(f));
}

void Master::Stub::async::setSaveState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setSaveState_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::PrepareAsyncsetSaveStateRaw(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::DisplayStateMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setSaveState_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::AsyncsetSaveStateRaw(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetSaveStateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Master::Stub::setRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::DisplayStateMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setRestoreState_, context, request, response);
}

void Master::Stub::async::setRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::DisplayStateMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setRestoreState_, context, request, response, std::move(f));
}

void Master::Stub::async::setRestoreState(::grpc::ClientContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setRestoreState_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::PrepareAsyncsetRestoreStateRaw(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::DisplayStateMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setRestoreState_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Master::Stub::AsyncsetRestoreStateRaw(::grpc::ClientContext* context, const ::NX::DisplayStateMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetRestoreStateRaw(context, request, cq);
  result->StartCall();
  return result;
}

Master::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Master_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Master::Service, ::NX::EmptyMsg, ::NX::BoolMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Master::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::BoolMsg* resp) {
               return service->connectTest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Master_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Master::Service, ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Master::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->updateForRescan(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Master_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Master::Service, ::NX::BoolMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Master::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::BoolMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->updatePortSelectionBoxes(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Master_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Master::Service, ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Master::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->reset(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Master_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Master::Service, ::NX::EmptyMsg, ::NX::YScaleUsedMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Master::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::YScaleUsedMsg* resp) {
               return service->loadWaveformData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Master_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Master::Service, ::NX::SampleMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Master::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::SampleMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->updatePlugin(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Master_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Master::Service, ::NX::LoadWaveformDataFromMemoryMsg, ::NX::YScaleUsedMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Master::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::LoadWaveformDataFromMemoryMsg* req,
             ::NX::YScaleUsedMsg* resp) {
               return service->loadWaveformDataFromMemory(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Master_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Master::Service, ::NX::DisplayStateMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Master::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::DisplayStateMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->setSaveState(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Master_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Master::Service, ::NX::DisplayStateMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Master::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::DisplayStateMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->setRestoreState(ctx, req, resp);
             }, this)));
}

Master::Service::~Service() {
}

::grpc::Status Master::Service::connectTest(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::BoolMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Master::Service::updateForRescan(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Master::Service::updatePortSelectionBoxes(::grpc::ServerContext* context, const ::NX::BoolMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Master::Service::reset(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Master::Service::loadWaveformData(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::YScaleUsedMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Master::Service::updatePlugin(::grpc::ServerContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Master::Service::loadWaveformDataFromMemory(::grpc::ServerContext* context, const ::NX::LoadWaveformDataFromMemoryMsg* request, ::NX::YScaleUsedMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Master::Service::setSaveState(::grpc::ServerContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Master::Service::setRestoreState(::grpc::ServerContext* context, const ::NX::DisplayStateMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace NX

