// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Recorder.proto

#include "Recorder.pb.h"
#include "Recorder.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace NX {

static const char* Recorder_method_names[] = {
  "/NX.Recorder/connectTest",
  "/NX.Recorder/initBoard",
  "/NX.Recorder/setSamplesPerRefresh",
  "/NX.Recorder/setMaxSamplesPerRefresh",
  "/NX.Recorder/setSamplesPerFullRefresh",
  "/NX.Recorder/setChannelEnabled",
  "/NX.Recorder/numGroups",
  "/NX.Recorder/numBaseGroups",
  "/NX.Recorder/numPortGroups",
  "/NX.Recorder/setSelectedEntireGroupID",
  "/NX.Recorder/getNextAvailableGroupID",
  "/NX.Recorder/populatedGroupList",
  "/NX.Recorder/populatedGroupListWithChannelCounts",
  "/NX.Recorder/headstageSignalNameList",
  "/NX.Recorder/controllerIOSignalNameList",
  "/NX.Recorder/getDisplayListAmplifiers",
  "/NX.Recorder/getDisplayListAmplifiersNoFilters",
  "/NX.Recorder/getDisplayListAuxInputs",
  "/NX.Recorder/getDisplayListSupplyVoltages",
  "/NX.Recorder/getDisplayListBaseGroup",
  "/NX.Recorder/retractLastPush",
  "/NX.Recorder/pushStateToUndoStack",
  "/NX.Recorder/clearUndoStack",
};

std::unique_ptr< Recorder::Stub> Recorder::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Recorder::Stub> stub(new Recorder::Stub(channel, options));
  return stub;
}

Recorder::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_connectTest_(Recorder_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_initBoard_(Recorder_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setSamplesPerRefresh_(Recorder_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setMaxSamplesPerRefresh_(Recorder_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setSamplesPerFullRefresh_(Recorder_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setChannelEnabled_(Recorder_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_numGroups_(Recorder_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_numBaseGroups_(Recorder_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_numPortGroups_(Recorder_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_setSelectedEntireGroupID_(Recorder_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getNextAvailableGroupID_(Recorder_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_populatedGroupList_(Recorder_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_populatedGroupListWithChannelCounts_(Recorder_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_headstageSignalNameList_(Recorder_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_controllerIOSignalNameList_(Recorder_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getDisplayListAmplifiers_(Recorder_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getDisplayListAmplifiersNoFilters_(Recorder_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getDisplayListAuxInputs_(Recorder_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getDisplayListSupplyVoltages_(Recorder_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_getDisplayListBaseGroup_(Recorder_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_retractLastPush_(Recorder_method_names[20], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_pushStateToUndoStack_(Recorder_method_names[21], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_clearUndoStack_(Recorder_method_names[22], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Recorder::Stub::connectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::BoolMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::BoolMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_connectTest_, context, request, response);
}

void Recorder::Stub::async::connectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::BoolMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::BoolMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_connectTest_, context, request, response, std::move(f));
}

void Recorder::Stub::async::connectTest(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::BoolMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_connectTest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::BoolMsg>* Recorder::Stub::PrepareAsyncconnectTestRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::BoolMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_connectTest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::BoolMsg>* Recorder::Stub::AsyncconnectTestRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncconnectTestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::initBoard(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::SignalsMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::SignalsMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_initBoard_, context, request, response);
}

void Recorder::Stub::async::initBoard(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::SignalsMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::SignalsMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_initBoard_, context, request, response, std::move(f));
}

void Recorder::Stub::async::initBoard(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::SignalsMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_initBoard_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::SignalsMsg>* Recorder::Stub::PrepareAsyncinitBoardRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::SignalsMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_initBoard_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::SignalsMsg>* Recorder::Stub::AsyncinitBoardRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncinitBoardRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::setSamplesPerRefresh(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::SampleMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setSamplesPerRefresh_, context, request, response);
}

void Recorder::Stub::async::setSamplesPerRefresh(::grpc::ClientContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::SampleMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setSamplesPerRefresh_, context, request, response, std::move(f));
}

void Recorder::Stub::async::setSamplesPerRefresh(::grpc::ClientContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setSamplesPerRefresh_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::PrepareAsyncsetSamplesPerRefreshRaw(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::SampleMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setSamplesPerRefresh_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::AsyncsetSamplesPerRefreshRaw(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetSamplesPerRefreshRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::setMaxSamplesPerRefresh(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::SampleMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setMaxSamplesPerRefresh_, context, request, response);
}

void Recorder::Stub::async::setMaxSamplesPerRefresh(::grpc::ClientContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::SampleMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setMaxSamplesPerRefresh_, context, request, response, std::move(f));
}

void Recorder::Stub::async::setMaxSamplesPerRefresh(::grpc::ClientContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setMaxSamplesPerRefresh_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::PrepareAsyncsetMaxSamplesPerRefreshRaw(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::SampleMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setMaxSamplesPerRefresh_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::AsyncsetMaxSamplesPerRefreshRaw(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetMaxSamplesPerRefreshRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::setSamplesPerFullRefresh(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::SampleMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setSamplesPerFullRefresh_, context, request, response);
}

void Recorder::Stub::async::setSamplesPerFullRefresh(::grpc::ClientContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::SampleMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setSamplesPerFullRefresh_, context, request, response, std::move(f));
}

void Recorder::Stub::async::setSamplesPerFullRefresh(::grpc::ClientContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setSamplesPerFullRefresh_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::PrepareAsyncsetSamplesPerFullRefreshRaw(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::SampleMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setSamplesPerFullRefresh_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::AsyncsetSamplesPerFullRefreshRaw(::grpc::ClientContext* context, const ::NX::SampleMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetSamplesPerFullRefreshRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::setChannelEnabled(::grpc::ClientContext* context, const ::NX::SetChannelEnabledMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::SetChannelEnabledMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setChannelEnabled_, context, request, response);
}

void Recorder::Stub::async::setChannelEnabled(::grpc::ClientContext* context, const ::NX::SetChannelEnabledMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::SetChannelEnabledMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setChannelEnabled_, context, request, response, std::move(f));
}

void Recorder::Stub::async::setChannelEnabled(::grpc::ClientContext* context, const ::NX::SetChannelEnabledMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setChannelEnabled_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::PrepareAsyncsetChannelEnabledRaw(::grpc::ClientContext* context, const ::NX::SetChannelEnabledMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::SetChannelEnabledMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setChannelEnabled_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::AsyncsetChannelEnabledRaw(::grpc::ClientContext* context, const ::NX::SetChannelEnabledMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetChannelEnabledRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::numGroups(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::IntMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::IntMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_numGroups_, context, request, response);
}

void Recorder::Stub::async::numGroups(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::IntMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::IntMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_numGroups_, context, request, response, std::move(f));
}

void Recorder::Stub::async::numGroups(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::IntMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_numGroups_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::IntMsg>* Recorder::Stub::PrepareAsyncnumGroupsRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::IntMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_numGroups_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::IntMsg>* Recorder::Stub::AsyncnumGroupsRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncnumGroupsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::numBaseGroups(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::IntMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::IntMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_numBaseGroups_, context, request, response);
}

void Recorder::Stub::async::numBaseGroups(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::IntMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::IntMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_numBaseGroups_, context, request, response, std::move(f));
}

void Recorder::Stub::async::numBaseGroups(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::IntMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_numBaseGroups_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::IntMsg>* Recorder::Stub::PrepareAsyncnumBaseGroupsRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::IntMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_numBaseGroups_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::IntMsg>* Recorder::Stub::AsyncnumBaseGroupsRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncnumBaseGroupsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::numPortGroups(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::IntMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::IntMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_numPortGroups_, context, request, response);
}

void Recorder::Stub::async::numPortGroups(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::IntMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::IntMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_numPortGroups_, context, request, response, std::move(f));
}

void Recorder::Stub::async::numPortGroups(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::IntMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_numPortGroups_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::IntMsg>* Recorder::Stub::PrepareAsyncnumPortGroupsRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::IntMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_numPortGroups_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::IntMsg>* Recorder::Stub::AsyncnumPortGroupsRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncnumPortGroupsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::setSelectedEntireGroupID(::grpc::ClientContext* context, const ::NX::SetSelectedEntireGroupIdMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::SetSelectedEntireGroupIdMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_setSelectedEntireGroupID_, context, request, response);
}

void Recorder::Stub::async::setSelectedEntireGroupID(::grpc::ClientContext* context, const ::NX::SetSelectedEntireGroupIdMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::SetSelectedEntireGroupIdMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setSelectedEntireGroupID_, context, request, response, std::move(f));
}

void Recorder::Stub::async::setSelectedEntireGroupID(::grpc::ClientContext* context, const ::NX::SetSelectedEntireGroupIdMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_setSelectedEntireGroupID_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::PrepareAsyncsetSelectedEntireGroupIDRaw(::grpc::ClientContext* context, const ::NX::SetSelectedEntireGroupIdMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::SetSelectedEntireGroupIdMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_setSelectedEntireGroupID_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::AsyncsetSelectedEntireGroupIDRaw(::grpc::ClientContext* context, const ::NX::SetSelectedEntireGroupIdMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsetSelectedEntireGroupIDRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::getNextAvailableGroupID(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::IntMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::IntMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getNextAvailableGroupID_, context, request, response);
}

void Recorder::Stub::async::getNextAvailableGroupID(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::IntMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::IntMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getNextAvailableGroupID_, context, request, response, std::move(f));
}

void Recorder::Stub::async::getNextAvailableGroupID(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::IntMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getNextAvailableGroupID_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::IntMsg>* Recorder::Stub::PrepareAsyncgetNextAvailableGroupIDRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::IntMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getNextAvailableGroupID_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::IntMsg>* Recorder::Stub::AsyncgetNextAvailableGroupIDRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetNextAvailableGroupIDRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::populatedGroupList(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::StringListMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_populatedGroupList_, context, request, response);
}

void Recorder::Stub::async::populatedGroupList(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::StringListMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_populatedGroupList_, context, request, response, std::move(f));
}

void Recorder::Stub::async::populatedGroupList(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::StringListMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_populatedGroupList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::PrepareAsyncpopulatedGroupListRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::StringListMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_populatedGroupList_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::AsyncpopulatedGroupListRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncpopulatedGroupListRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::populatedGroupListWithChannelCounts(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::StringListMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_populatedGroupListWithChannelCounts_, context, request, response);
}

void Recorder::Stub::async::populatedGroupListWithChannelCounts(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::StringListMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_populatedGroupListWithChannelCounts_, context, request, response, std::move(f));
}

void Recorder::Stub::async::populatedGroupListWithChannelCounts(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::StringListMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_populatedGroupListWithChannelCounts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::PrepareAsyncpopulatedGroupListWithChannelCountsRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::StringListMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_populatedGroupListWithChannelCounts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::AsyncpopulatedGroupListWithChannelCountsRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncpopulatedGroupListWithChannelCountsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::headstageSignalNameList(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::NX::StringListMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_headstageSignalNameList_, context, request, response);
}

void Recorder::Stub::async::headstageSignalNameList(::grpc::ClientContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_headstageSignalNameList_, context, request, response, std::move(f));
}

void Recorder::Stub::async::headstageSignalNameList(::grpc::ClientContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_headstageSignalNameList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::PrepareAsyncheadstageSignalNameListRaw(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::StringListMsg, ::NX::StringMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_headstageSignalNameList_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::AsyncheadstageSignalNameListRaw(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncheadstageSignalNameListRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::controllerIOSignalNameList(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::StringListMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_controllerIOSignalNameList_, context, request, response);
}

void Recorder::Stub::async::controllerIOSignalNameList(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::StringListMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_controllerIOSignalNameList_, context, request, response, std::move(f));
}

void Recorder::Stub::async::controllerIOSignalNameList(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::StringListMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_controllerIOSignalNameList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::PrepareAsynccontrollerIOSignalNameListRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::StringListMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_controllerIOSignalNameList_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::AsynccontrollerIOSignalNameListRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccontrollerIOSignalNameListRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::getDisplayListAmplifiers(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::NX::StringListMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getDisplayListAmplifiers_, context, request, response);
}

void Recorder::Stub::async::getDisplayListAmplifiers(::grpc::ClientContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getDisplayListAmplifiers_, context, request, response, std::move(f));
}

void Recorder::Stub::async::getDisplayListAmplifiers(::grpc::ClientContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getDisplayListAmplifiers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::PrepareAsyncgetDisplayListAmplifiersRaw(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::StringListMsg, ::NX::StringMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getDisplayListAmplifiers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::AsyncgetDisplayListAmplifiersRaw(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetDisplayListAmplifiersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::getDisplayListAmplifiersNoFilters(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::NX::StringListMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getDisplayListAmplifiersNoFilters_, context, request, response);
}

void Recorder::Stub::async::getDisplayListAmplifiersNoFilters(::grpc::ClientContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getDisplayListAmplifiersNoFilters_, context, request, response, std::move(f));
}

void Recorder::Stub::async::getDisplayListAmplifiersNoFilters(::grpc::ClientContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getDisplayListAmplifiersNoFilters_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::PrepareAsyncgetDisplayListAmplifiersNoFiltersRaw(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::StringListMsg, ::NX::StringMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getDisplayListAmplifiersNoFilters_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::AsyncgetDisplayListAmplifiersNoFiltersRaw(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetDisplayListAmplifiersNoFiltersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::getDisplayListAuxInputs(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::NX::StringListMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getDisplayListAuxInputs_, context, request, response);
}

void Recorder::Stub::async::getDisplayListAuxInputs(::grpc::ClientContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getDisplayListAuxInputs_, context, request, response, std::move(f));
}

void Recorder::Stub::async::getDisplayListAuxInputs(::grpc::ClientContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getDisplayListAuxInputs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::PrepareAsyncgetDisplayListAuxInputsRaw(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::StringListMsg, ::NX::StringMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getDisplayListAuxInputs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::AsyncgetDisplayListAuxInputsRaw(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetDisplayListAuxInputsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::getDisplayListSupplyVoltages(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::NX::StringListMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getDisplayListSupplyVoltages_, context, request, response);
}

void Recorder::Stub::async::getDisplayListSupplyVoltages(::grpc::ClientContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getDisplayListSupplyVoltages_, context, request, response, std::move(f));
}

void Recorder::Stub::async::getDisplayListSupplyVoltages(::grpc::ClientContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getDisplayListSupplyVoltages_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::PrepareAsyncgetDisplayListSupplyVoltagesRaw(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::StringListMsg, ::NX::StringMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getDisplayListSupplyVoltages_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::AsyncgetDisplayListSupplyVoltagesRaw(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetDisplayListSupplyVoltagesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::getDisplayListBaseGroup(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::NX::StringListMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getDisplayListBaseGroup_, context, request, response);
}

void Recorder::Stub::async::getDisplayListBaseGroup(::grpc::ClientContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getDisplayListBaseGroup_, context, request, response, std::move(f));
}

void Recorder::Stub::async::getDisplayListBaseGroup(::grpc::ClientContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getDisplayListBaseGroup_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::PrepareAsyncgetDisplayListBaseGroupRaw(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::StringListMsg, ::NX::StringMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getDisplayListBaseGroup_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::StringListMsg>* Recorder::Stub::AsyncgetDisplayListBaseGroupRaw(::grpc::ClientContext* context, const ::NX::StringMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetDisplayListBaseGroupRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::retractLastPush(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_retractLastPush_, context, request, response);
}

void Recorder::Stub::async::retractLastPush(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_retractLastPush_, context, request, response, std::move(f));
}

void Recorder::Stub::async::retractLastPush(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_retractLastPush_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::PrepareAsyncretractLastPushRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_retractLastPush_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::AsyncretractLastPushRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncretractLastPushRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::pushStateToUndoStack(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_pushStateToUndoStack_, context, request, response);
}

void Recorder::Stub::async::pushStateToUndoStack(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_pushStateToUndoStack_, context, request, response, std::move(f));
}

void Recorder::Stub::async::pushStateToUndoStack(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_pushStateToUndoStack_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::PrepareAsyncpushStateToUndoStackRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_pushStateToUndoStack_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::AsyncpushStateToUndoStackRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncpushStateToUndoStackRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Recorder::Stub::clearUndoStack(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::NX::EmptyMsg* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_clearUndoStack_, context, request, response);
}

void Recorder::Stub::async::clearUndoStack(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_clearUndoStack_, context, request, response, std::move(f));
}

void Recorder::Stub::async::clearUndoStack(::grpc::ClientContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_clearUndoStack_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::PrepareAsyncclearUndoStackRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_clearUndoStack_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NX::EmptyMsg>* Recorder::Stub::AsyncclearUndoStackRaw(::grpc::ClientContext* context, const ::NX::EmptyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncclearUndoStackRaw(context, request, cq);
  result->StartCall();
  return result;
}

Recorder::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::EmptyMsg, ::NX::BoolMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::BoolMsg* resp) {
               return service->connectTest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::EmptyMsg, ::NX::SignalsMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::SignalsMsg* resp) {
               return service->initBoard(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::SampleMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::SampleMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->setSamplesPerRefresh(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::SampleMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::SampleMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->setMaxSamplesPerRefresh(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::SampleMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::SampleMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->setSamplesPerFullRefresh(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::SetChannelEnabledMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::SetChannelEnabledMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->setChannelEnabled(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::EmptyMsg, ::NX::IntMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::IntMsg* resp) {
               return service->numGroups(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::EmptyMsg, ::NX::IntMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::IntMsg* resp) {
               return service->numBaseGroups(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::EmptyMsg, ::NX::IntMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::IntMsg* resp) {
               return service->numPortGroups(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::SetSelectedEntireGroupIdMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::SetSelectedEntireGroupIdMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->setSelectedEntireGroupID(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::EmptyMsg, ::NX::IntMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::IntMsg* resp) {
               return service->getNextAvailableGroupID(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::EmptyMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::StringListMsg* resp) {
               return service->populatedGroupList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::EmptyMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::StringListMsg* resp) {
               return service->populatedGroupListWithChannelCounts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::StringMsg* req,
             ::NX::StringListMsg* resp) {
               return service->headstageSignalNameList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::EmptyMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::StringListMsg* resp) {
               return service->controllerIOSignalNameList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::StringMsg* req,
             ::NX::StringListMsg* resp) {
               return service->getDisplayListAmplifiers(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::StringMsg* req,
             ::NX::StringListMsg* resp) {
               return service->getDisplayListAmplifiersNoFilters(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::StringMsg* req,
             ::NX::StringListMsg* resp) {
               return service->getDisplayListAuxInputs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::StringMsg* req,
             ::NX::StringListMsg* resp) {
               return service->getDisplayListSupplyVoltages(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[19],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::StringMsg, ::NX::StringListMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::StringMsg* req,
             ::NX::StringListMsg* resp) {
               return service->getDisplayListBaseGroup(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[20],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->retractLastPush(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[21],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->pushStateToUndoStack(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Recorder_method_names[22],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Recorder::Service, ::NX::EmptyMsg, ::NX::EmptyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Recorder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NX::EmptyMsg* req,
             ::NX::EmptyMsg* resp) {
               return service->clearUndoStack(ctx, req, resp);
             }, this)));
}

Recorder::Service::~Service() {
}

::grpc::Status Recorder::Service::connectTest(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::BoolMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::initBoard(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::SignalsMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::setSamplesPerRefresh(::grpc::ServerContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::setMaxSamplesPerRefresh(::grpc::ServerContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::setSamplesPerFullRefresh(::grpc::ServerContext* context, const ::NX::SampleMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::setChannelEnabled(::grpc::ServerContext* context, const ::NX::SetChannelEnabledMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::numGroups(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::IntMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::numBaseGroups(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::IntMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::numPortGroups(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::IntMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::setSelectedEntireGroupID(::grpc::ServerContext* context, const ::NX::SetSelectedEntireGroupIdMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::getNextAvailableGroupID(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::IntMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::populatedGroupList(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::StringListMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::populatedGroupListWithChannelCounts(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::StringListMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::headstageSignalNameList(::grpc::ServerContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::controllerIOSignalNameList(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::StringListMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::getDisplayListAmplifiers(::grpc::ServerContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::getDisplayListAmplifiersNoFilters(::grpc::ServerContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::getDisplayListAuxInputs(::grpc::ServerContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::getDisplayListSupplyVoltages(::grpc::ServerContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::getDisplayListBaseGroup(::grpc::ServerContext* context, const ::NX::StringMsg* request, ::NX::StringListMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::retractLastPush(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::pushStateToUndoStack(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Recorder::Service::clearUndoStack(::grpc::ServerContext* context, const ::NX::EmptyMsg* request, ::NX::EmptyMsg* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace NX

