// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Master.proto

#include "Master.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace NX {
}  // namespace NX
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Master_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Master_2eproto = nullptr;
const uint32_t TableStruct_Master_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Master_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014Master.proto\022\002NX\032\017NxMessage.proto2\356\003\n\006"
  "Master\022*\n\013connectTest\022\014.NX.EmptyMsg\032\013.NX"
  ".BoolMsg\"\000\022/\n\017updateForRescan\022\014.NX.Empty"
  "Msg\032\014.NX.EmptyMsg\"\000\0227\n\030updatePortSelecti"
  "onBoxes\022\013.NX.BoolMsg\032\014.NX.EmptyMsg\"\000\022%\n\005"
  "reset\022\014.NX.EmptyMsg\032\014.NX.EmptyMsg\"\000\0225\n\020l"
  "oadWaveformData\022\014.NX.EmptyMsg\032\021.NX.YScal"
  "eUsedMsg\"\000\022-\n\014updatePlugin\022\r.NX.SampleMs"
  "g\032\014.NX.EmptyMsg\"\000\022T\n\032loadWaveformDataFro"
  "mMemory\022!.NX.LoadWaveformDataFromMemoryM"
  "sg\032\021.NX.YScaleUsedMsg\"\000\0223\n\014setSaveState\022"
  "\023.NX.DisplayStateMsg\032\014.NX.EmptyMsg\"\000\0226\n\017"
  "setRestoreState\022\023.NX.DisplayStateMsg\032\014.N"
  "X.EmptyMsg\"\000B\020\n\016io.grpc.masterb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Master_2eproto_deps[1] = {
  &::descriptor_table_NxMessage_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Master_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Master_2eproto = {
  false, false, 558, descriptor_table_protodef_Master_2eproto, "Master.proto", 
  &descriptor_table_Master_2eproto_once, descriptor_table_Master_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_Master_2eproto::offsets,
  nullptr, file_level_enum_descriptors_Master_2eproto, file_level_service_descriptors_Master_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_Master_2eproto_getter() {
  return &descriptor_table_Master_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Master_2eproto(&descriptor_table_Master_2eproto);
namespace NX {

// @@protoc_insertion_point(namespace_scope)
}  // namespace NX
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
