// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Recorder.proto

#include "Recorder.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace NX {
constexpr SetChannelEnabledMsg::SetChannelEnabledMsg(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : groupid_(0)
  , nativechannelnum_(0){}
struct SetChannelEnabledMsgDefaultTypeInternal {
  constexpr SetChannelEnabledMsgDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SetChannelEnabledMsgDefaultTypeInternal() {}
  union {
    SetChannelEnabledMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SetChannelEnabledMsgDefaultTypeInternal _SetChannelEnabledMsg_default_instance_;
constexpr SetSelectedEntireGroupIdMsg::SetSelectedEntireGroupIdMsg(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : wavename_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , select_(false){}
struct SetSelectedEntireGroupIdMsgDefaultTypeInternal {
  constexpr SetSelectedEntireGroupIdMsgDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SetSelectedEntireGroupIdMsgDefaultTypeInternal() {}
  union {
    SetSelectedEntireGroupIdMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SetSelectedEntireGroupIdMsgDefaultTypeInternal _SetSelectedEntireGroupIdMsg_default_instance_;
}  // namespace NX
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Recorder_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Recorder_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Recorder_2eproto = nullptr;

const uint32_t TableStruct_Recorder_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::NX::SetChannelEnabledMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::NX::SetChannelEnabledMsg, groupid_),
  PROTOBUF_FIELD_OFFSET(::NX::SetChannelEnabledMsg, nativechannelnum_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::NX::SetSelectedEntireGroupIdMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::NX::SetSelectedEntireGroupIdMsg, wavename_),
  PROTOBUF_FIELD_OFFSET(::NX::SetSelectedEntireGroupIdMsg, select_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::NX::SetChannelEnabledMsg)},
  { 8, -1, -1, sizeof(::NX::SetSelectedEntireGroupIdMsg)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::NX::_SetChannelEnabledMsg_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::NX::_SetSelectedEntireGroupIdMsg_default_instance_),
};

const char descriptor_table_protodef_Recorder_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016Recorder.proto\022\002NX\032\017NxMessage.proto\"A\n"
  "\024SetChannelEnabledMsg\022\017\n\007groupID\030\001 \001(\005\022\030"
  "\n\020nativeChannelNum\030\002 \001(\005\"\?\n\033SetSelectedE"
  "ntireGroupIdMsg\022\020\n\010waveName\030\001 \001(\t\022\016\n\006sel"
  "ect\030\002 \001(\0102\272\n\n\010Recorder\022*\n\013connectTest\022\014."
  "NX.EmptyMsg\032\013.NX.BoolMsg\"\000\022+\n\tinitBoard\022"
  "\014.NX.EmptyMsg\032\016.NX.SignalsMsg\"\000\0225\n\024setSa"
  "mplesPerRefresh\022\r.NX.SampleMsg\032\014.NX.Empt"
  "yMsg\"\000\0228\n\027setMaxSamplesPerRefresh\022\r.NX.S"
  "ampleMsg\032\014.NX.EmptyMsg\"\000\0229\n\030setSamplesPe"
  "rFullRefresh\022\r.NX.SampleMsg\032\014.NX.EmptyMs"
  "g\"\000\022=\n\021setChannelEnabled\022\030.NX.SetChannel"
  "EnabledMsg\032\014.NX.EmptyMsg\"\000\022\'\n\tnumGroups\022"
  "\014.NX.EmptyMsg\032\n.NX.IntMsg\"\000\022+\n\rnumBaseGr"
  "oups\022\014.NX.EmptyMsg\032\n.NX.IntMsg\"\000\022+\n\rnumP"
  "ortGroups\022\014.NX.EmptyMsg\032\n.NX.IntMsg\"\000\022K\n"
  "\030setSelectedEntireGroupID\022\037.NX.SetSelect"
  "edEntireGroupIdMsg\032\014.NX.EmptyMsg\"\000\0225\n\027ge"
  "tNextAvailableGroupID\022\014.NX.EmptyMsg\032\n.NX"
  ".IntMsg\"\000\0227\n\022populatedGroupList\022\014.NX.Emp"
  "tyMsg\032\021.NX.StringListMsg\"\000\022H\n#populatedG"
  "roupListWithChannelCounts\022\014.NX.EmptyMsg\032"
  "\021.NX.StringListMsg\"\000\022=\n\027headstageSignalN"
  "ameList\022\r.NX.StringMsg\032\021.NX.StringListMs"
  "g\"\000\022\?\n\032controllerIOSignalNameList\022\014.NX.E"
  "mptyMsg\032\021.NX.StringListMsg\"\000\022>\n\030getDispl"
  "ayListAmplifiers\022\r.NX.StringMsg\032\021.NX.Str"
  "ingListMsg\"\000\022G\n!getDisplayListAmplifiers"
  "NoFilters\022\r.NX.StringMsg\032\021.NX.StringList"
  "Msg\"\000\022=\n\027getDisplayListAuxInputs\022\r.NX.St"
  "ringMsg\032\021.NX.StringListMsg\"\000\022B\n\034getDispl"
  "ayListSupplyVoltages\022\r.NX.StringMsg\032\021.NX"
  ".StringListMsg\"\000\022=\n\027getDisplayListBaseGr"
  "oup\022\r.NX.StringMsg\032\021.NX.StringListMsg\"\000\022"
  "/\n\017retractLastPush\022\014.NX.EmptyMsg\032\014.NX.Em"
  "ptyMsg\"\000\0224\n\024pushStateToUndoStack\022\014.NX.Em"
  "ptyMsg\032\014.NX.EmptyMsg\"\000\022.\n\016clearUndoStack"
  "\022\014.NX.EmptyMsg\032\014.NX.EmptyMsg\"\000B\022\n\020io.grp"
  "c.recorderb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Recorder_2eproto_deps[1] = {
  &::descriptor_table_NxMessage_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Recorder_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Recorder_2eproto = {
  false, false, 1538, descriptor_table_protodef_Recorder_2eproto, "Recorder.proto", 
  &descriptor_table_Recorder_2eproto_once, descriptor_table_Recorder_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_Recorder_2eproto::offsets,
  file_level_metadata_Recorder_2eproto, file_level_enum_descriptors_Recorder_2eproto, file_level_service_descriptors_Recorder_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_Recorder_2eproto_getter() {
  return &descriptor_table_Recorder_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Recorder_2eproto(&descriptor_table_Recorder_2eproto);
namespace NX {

// ===================================================================

class SetChannelEnabledMsg::_Internal {
 public:
};

SetChannelEnabledMsg::SetChannelEnabledMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:NX.SetChannelEnabledMsg)
}
SetChannelEnabledMsg::SetChannelEnabledMsg(const SetChannelEnabledMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&groupid_, &from.groupid_,
    static_cast<size_t>(reinterpret_cast<char*>(&nativechannelnum_) -
    reinterpret_cast<char*>(&groupid_)) + sizeof(nativechannelnum_));
  // @@protoc_insertion_point(copy_constructor:NX.SetChannelEnabledMsg)
}

inline void SetChannelEnabledMsg::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&groupid_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&nativechannelnum_) -
    reinterpret_cast<char*>(&groupid_)) + sizeof(nativechannelnum_));
}

SetChannelEnabledMsg::~SetChannelEnabledMsg() {
  // @@protoc_insertion_point(destructor:NX.SetChannelEnabledMsg)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SetChannelEnabledMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SetChannelEnabledMsg::ArenaDtor(void* object) {
  SetChannelEnabledMsg* _this = reinterpret_cast< SetChannelEnabledMsg* >(object);
  (void)_this;
}
void SetChannelEnabledMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SetChannelEnabledMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SetChannelEnabledMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:NX.SetChannelEnabledMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&groupid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&nativechannelnum_) -
      reinterpret_cast<char*>(&groupid_)) + sizeof(nativechannelnum_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SetChannelEnabledMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 groupID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          groupid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 nativeChannelNum = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          nativechannelnum_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SetChannelEnabledMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NX.SetChannelEnabledMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 groupID = 1;
  if (this->_internal_groupid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_groupid(), target);
  }

  // int32 nativeChannelNum = 2;
  if (this->_internal_nativechannelnum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_nativechannelnum(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NX.SetChannelEnabledMsg)
  return target;
}

size_t SetChannelEnabledMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NX.SetChannelEnabledMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 groupID = 1;
  if (this->_internal_groupid() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_groupid());
  }

  // int32 nativeChannelNum = 2;
  if (this->_internal_nativechannelnum() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_nativechannelnum());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SetChannelEnabledMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SetChannelEnabledMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SetChannelEnabledMsg::GetClassData() const { return &_class_data_; }

void SetChannelEnabledMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SetChannelEnabledMsg *>(to)->MergeFrom(
      static_cast<const SetChannelEnabledMsg &>(from));
}


void SetChannelEnabledMsg::MergeFrom(const SetChannelEnabledMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NX.SetChannelEnabledMsg)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_groupid() != 0) {
    _internal_set_groupid(from._internal_groupid());
  }
  if (from._internal_nativechannelnum() != 0) {
    _internal_set_nativechannelnum(from._internal_nativechannelnum());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SetChannelEnabledMsg::CopyFrom(const SetChannelEnabledMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NX.SetChannelEnabledMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetChannelEnabledMsg::IsInitialized() const {
  return true;
}

void SetChannelEnabledMsg::InternalSwap(SetChannelEnabledMsg* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SetChannelEnabledMsg, nativechannelnum_)
      + sizeof(SetChannelEnabledMsg::nativechannelnum_)
      - PROTOBUF_FIELD_OFFSET(SetChannelEnabledMsg, groupid_)>(
          reinterpret_cast<char*>(&groupid_),
          reinterpret_cast<char*>(&other->groupid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SetChannelEnabledMsg::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_Recorder_2eproto_getter, &descriptor_table_Recorder_2eproto_once,
      file_level_metadata_Recorder_2eproto[0]);
}

// ===================================================================

class SetSelectedEntireGroupIdMsg::_Internal {
 public:
};

SetSelectedEntireGroupIdMsg::SetSelectedEntireGroupIdMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:NX.SetSelectedEntireGroupIdMsg)
}
SetSelectedEntireGroupIdMsg::SetSelectedEntireGroupIdMsg(const SetSelectedEntireGroupIdMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  wavename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    wavename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_wavename().empty()) {
    wavename_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_wavename(), 
      GetArenaForAllocation());
  }
  select_ = from.select_;
  // @@protoc_insertion_point(copy_constructor:NX.SetSelectedEntireGroupIdMsg)
}

inline void SetSelectedEntireGroupIdMsg::SharedCtor() {
wavename_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  wavename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
select_ = false;
}

SetSelectedEntireGroupIdMsg::~SetSelectedEntireGroupIdMsg() {
  // @@protoc_insertion_point(destructor:NX.SetSelectedEntireGroupIdMsg)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SetSelectedEntireGroupIdMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  wavename_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SetSelectedEntireGroupIdMsg::ArenaDtor(void* object) {
  SetSelectedEntireGroupIdMsg* _this = reinterpret_cast< SetSelectedEntireGroupIdMsg* >(object);
  (void)_this;
}
void SetSelectedEntireGroupIdMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SetSelectedEntireGroupIdMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SetSelectedEntireGroupIdMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:NX.SetSelectedEntireGroupIdMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  wavename_.ClearToEmpty();
  select_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SetSelectedEntireGroupIdMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string waveName = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_wavename();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NX.SetSelectedEntireGroupIdMsg.waveName"));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool select = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          select_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SetSelectedEntireGroupIdMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NX.SetSelectedEntireGroupIdMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string waveName = 1;
  if (!this->_internal_wavename().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_wavename().data(), static_cast<int>(this->_internal_wavename().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NX.SetSelectedEntireGroupIdMsg.waveName");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_wavename(), target);
  }

  // bool select = 2;
  if (this->_internal_select() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_select(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NX.SetSelectedEntireGroupIdMsg)
  return target;
}

size_t SetSelectedEntireGroupIdMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NX.SetSelectedEntireGroupIdMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string waveName = 1;
  if (!this->_internal_wavename().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_wavename());
  }

  // bool select = 2;
  if (this->_internal_select() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SetSelectedEntireGroupIdMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SetSelectedEntireGroupIdMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SetSelectedEntireGroupIdMsg::GetClassData() const { return &_class_data_; }

void SetSelectedEntireGroupIdMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SetSelectedEntireGroupIdMsg *>(to)->MergeFrom(
      static_cast<const SetSelectedEntireGroupIdMsg &>(from));
}


void SetSelectedEntireGroupIdMsg::MergeFrom(const SetSelectedEntireGroupIdMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NX.SetSelectedEntireGroupIdMsg)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_wavename().empty()) {
    _internal_set_wavename(from._internal_wavename());
  }
  if (from._internal_select() != 0) {
    _internal_set_select(from._internal_select());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SetSelectedEntireGroupIdMsg::CopyFrom(const SetSelectedEntireGroupIdMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NX.SetSelectedEntireGroupIdMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetSelectedEntireGroupIdMsg::IsInitialized() const {
  return true;
}

void SetSelectedEntireGroupIdMsg::InternalSwap(SetSelectedEntireGroupIdMsg* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &wavename_, lhs_arena,
      &other->wavename_, rhs_arena
  );
  swap(select_, other->select_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SetSelectedEntireGroupIdMsg::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_Recorder_2eproto_getter, &descriptor_table_Recorder_2eproto_once,
      file_level_metadata_Recorder_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace NX
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::NX::SetChannelEnabledMsg* Arena::CreateMaybeMessage< ::NX::SetChannelEnabledMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NX::SetChannelEnabledMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::NX::SetSelectedEntireGroupIdMsg* Arena::CreateMaybeMessage< ::NX::SetSelectedEntireGroupIdMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NX::SetSelectedEntireGroupIdMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
