// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Recorder.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Recorder_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Recorder_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "NxMessage.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Recorder_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Recorder_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Recorder_2eproto;
namespace NX {
class SetChannelEnabledMsg;
struct SetChannelEnabledMsgDefaultTypeInternal;
extern SetChannelEnabledMsgDefaultTypeInternal _SetChannelEnabledMsg_default_instance_;
class SetSelectedEntireGroupIdMsg;
struct SetSelectedEntireGroupIdMsgDefaultTypeInternal;
extern SetSelectedEntireGroupIdMsgDefaultTypeInternal _SetSelectedEntireGroupIdMsg_default_instance_;
}  // namespace NX
PROTOBUF_NAMESPACE_OPEN
template<> ::NX::SetChannelEnabledMsg* Arena::CreateMaybeMessage<::NX::SetChannelEnabledMsg>(Arena*);
template<> ::NX::SetSelectedEntireGroupIdMsg* Arena::CreateMaybeMessage<::NX::SetSelectedEntireGroupIdMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace NX {

// ===================================================================

class SetChannelEnabledMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NX.SetChannelEnabledMsg) */ {
 public:
  inline SetChannelEnabledMsg() : SetChannelEnabledMsg(nullptr) {}
  ~SetChannelEnabledMsg() override;
  explicit constexpr SetChannelEnabledMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SetChannelEnabledMsg(const SetChannelEnabledMsg& from);
  SetChannelEnabledMsg(SetChannelEnabledMsg&& from) noexcept
    : SetChannelEnabledMsg() {
    *this = ::std::move(from);
  }

  inline SetChannelEnabledMsg& operator=(const SetChannelEnabledMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetChannelEnabledMsg& operator=(SetChannelEnabledMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetChannelEnabledMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetChannelEnabledMsg* internal_default_instance() {
    return reinterpret_cast<const SetChannelEnabledMsg*>(
               &_SetChannelEnabledMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SetChannelEnabledMsg& a, SetChannelEnabledMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(SetChannelEnabledMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetChannelEnabledMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetChannelEnabledMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SetChannelEnabledMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SetChannelEnabledMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SetChannelEnabledMsg& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetChannelEnabledMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NX.SetChannelEnabledMsg";
  }
  protected:
  explicit SetChannelEnabledMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGroupIDFieldNumber = 1,
    kNativeChannelNumFieldNumber = 2,
  };
  // int32 groupID = 1;
  void clear_groupid();
  int32_t groupid() const;
  void set_groupid(int32_t value);
  private:
  int32_t _internal_groupid() const;
  void _internal_set_groupid(int32_t value);
  public:

  // int32 nativeChannelNum = 2;
  void clear_nativechannelnum();
  int32_t nativechannelnum() const;
  void set_nativechannelnum(int32_t value);
  private:
  int32_t _internal_nativechannelnum() const;
  void _internal_set_nativechannelnum(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:NX.SetChannelEnabledMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t groupid_;
  int32_t nativechannelnum_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Recorder_2eproto;
};
// -------------------------------------------------------------------

class SetSelectedEntireGroupIdMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NX.SetSelectedEntireGroupIdMsg) */ {
 public:
  inline SetSelectedEntireGroupIdMsg() : SetSelectedEntireGroupIdMsg(nullptr) {}
  ~SetSelectedEntireGroupIdMsg() override;
  explicit constexpr SetSelectedEntireGroupIdMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SetSelectedEntireGroupIdMsg(const SetSelectedEntireGroupIdMsg& from);
  SetSelectedEntireGroupIdMsg(SetSelectedEntireGroupIdMsg&& from) noexcept
    : SetSelectedEntireGroupIdMsg() {
    *this = ::std::move(from);
  }

  inline SetSelectedEntireGroupIdMsg& operator=(const SetSelectedEntireGroupIdMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetSelectedEntireGroupIdMsg& operator=(SetSelectedEntireGroupIdMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetSelectedEntireGroupIdMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetSelectedEntireGroupIdMsg* internal_default_instance() {
    return reinterpret_cast<const SetSelectedEntireGroupIdMsg*>(
               &_SetSelectedEntireGroupIdMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SetSelectedEntireGroupIdMsg& a, SetSelectedEntireGroupIdMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(SetSelectedEntireGroupIdMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetSelectedEntireGroupIdMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetSelectedEntireGroupIdMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SetSelectedEntireGroupIdMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SetSelectedEntireGroupIdMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SetSelectedEntireGroupIdMsg& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetSelectedEntireGroupIdMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NX.SetSelectedEntireGroupIdMsg";
  }
  protected:
  explicit SetSelectedEntireGroupIdMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWaveNameFieldNumber = 1,
    kSelectFieldNumber = 2,
  };
  // string waveName = 1;
  void clear_wavename();
  const std::string& wavename() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_wavename(ArgT0&& arg0, ArgT... args);
  std::string* mutable_wavename();
  PROTOBUF_NODISCARD std::string* release_wavename();
  void set_allocated_wavename(std::string* wavename);
  private:
  const std::string& _internal_wavename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_wavename(const std::string& value);
  std::string* _internal_mutable_wavename();
  public:

  // bool select = 2;
  void clear_select();
  bool select() const;
  void set_select(bool value);
  private:
  bool _internal_select() const;
  void _internal_set_select(bool value);
  public:

  // @@protoc_insertion_point(class_scope:NX.SetSelectedEntireGroupIdMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr wavename_;
  bool select_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Recorder_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SetChannelEnabledMsg

// int32 groupID = 1;
inline void SetChannelEnabledMsg::clear_groupid() {
  groupid_ = 0;
}
inline int32_t SetChannelEnabledMsg::_internal_groupid() const {
  return groupid_;
}
inline int32_t SetChannelEnabledMsg::groupid() const {
  // @@protoc_insertion_point(field_get:NX.SetChannelEnabledMsg.groupID)
  return _internal_groupid();
}
inline void SetChannelEnabledMsg::_internal_set_groupid(int32_t value) {
  
  groupid_ = value;
}
inline void SetChannelEnabledMsg::set_groupid(int32_t value) {
  _internal_set_groupid(value);
  // @@protoc_insertion_point(field_set:NX.SetChannelEnabledMsg.groupID)
}

// int32 nativeChannelNum = 2;
inline void SetChannelEnabledMsg::clear_nativechannelnum() {
  nativechannelnum_ = 0;
}
inline int32_t SetChannelEnabledMsg::_internal_nativechannelnum() const {
  return nativechannelnum_;
}
inline int32_t SetChannelEnabledMsg::nativechannelnum() const {
  // @@protoc_insertion_point(field_get:NX.SetChannelEnabledMsg.nativeChannelNum)
  return _internal_nativechannelnum();
}
inline void SetChannelEnabledMsg::_internal_set_nativechannelnum(int32_t value) {
  
  nativechannelnum_ = value;
}
inline void SetChannelEnabledMsg::set_nativechannelnum(int32_t value) {
  _internal_set_nativechannelnum(value);
  // @@protoc_insertion_point(field_set:NX.SetChannelEnabledMsg.nativeChannelNum)
}

// -------------------------------------------------------------------

// SetSelectedEntireGroupIdMsg

// string waveName = 1;
inline void SetSelectedEntireGroupIdMsg::clear_wavename() {
  wavename_.ClearToEmpty();
}
inline const std::string& SetSelectedEntireGroupIdMsg::wavename() const {
  // @@protoc_insertion_point(field_get:NX.SetSelectedEntireGroupIdMsg.waveName)
  return _internal_wavename();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SetSelectedEntireGroupIdMsg::set_wavename(ArgT0&& arg0, ArgT... args) {
 
 wavename_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:NX.SetSelectedEntireGroupIdMsg.waveName)
}
inline std::string* SetSelectedEntireGroupIdMsg::mutable_wavename() {
  std::string* _s = _internal_mutable_wavename();
  // @@protoc_insertion_point(field_mutable:NX.SetSelectedEntireGroupIdMsg.waveName)
  return _s;
}
inline const std::string& SetSelectedEntireGroupIdMsg::_internal_wavename() const {
  return wavename_.Get();
}
inline void SetSelectedEntireGroupIdMsg::_internal_set_wavename(const std::string& value) {
  
  wavename_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* SetSelectedEntireGroupIdMsg::_internal_mutable_wavename() {
  
  return wavename_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* SetSelectedEntireGroupIdMsg::release_wavename() {
  // @@protoc_insertion_point(field_release:NX.SetSelectedEntireGroupIdMsg.waveName)
  return wavename_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void SetSelectedEntireGroupIdMsg::set_allocated_wavename(std::string* wavename) {
  if (wavename != nullptr) {
    
  } else {
    
  }
  wavename_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), wavename,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (wavename_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    wavename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:NX.SetSelectedEntireGroupIdMsg.waveName)
}

// bool select = 2;
inline void SetSelectedEntireGroupIdMsg::clear_select() {
  select_ = false;
}
inline bool SetSelectedEntireGroupIdMsg::_internal_select() const {
  return select_;
}
inline bool SetSelectedEntireGroupIdMsg::select() const {
  // @@protoc_insertion_point(field_get:NX.SetSelectedEntireGroupIdMsg.select)
  return _internal_select();
}
inline void SetSelectedEntireGroupIdMsg::_internal_set_select(bool value) {
  
  select_ = value;
}
inline void SetSelectedEntireGroupIdMsg::set_select(bool value) {
  _internal_set_select(value);
  // @@protoc_insertion_point(field_set:NX.SetSelectedEntireGroupIdMsg.select)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace NX

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Recorder_2eproto
